/**
 * LaTeX completion data — commands, environments, packages and document classes.
 *
 * Pure data. This module deliberately imports nothing (least of all monaco): the
 * completion provider that consumes it is the only place that knows about
 * `CompletionItemKind`, ranges and insert rules, so this file stays cheap to
 * import from anywhere and trivial to test.
 *
 * The entries are hand-authored from general LaTeX knowledge rather than
 * generated from a package database — the aim is the ~300 commands people
 * actually type, each with a one-line description worth reading, not exhaustive
 * coverage of every control sequence in TeX Live.
 *
 * Snippets are Monaco/TextMate bodies: `$1`/`$2` tabstops, `$0` final cursor,
 * `${1:default}` placeholders. They are stored WITHOUT the leading backslash,
 * because the trigger character is typically already in the buffer — the
 * provider decides whether to re-emit it. A command that takes no arguments has
 * no `snippet` at all; the provider inserts the bare name.
 *
 * Environment `body` is likewise the text inserted between `\begin{name}` and
 * `\end{name}`. Since it lands immediately after `\begin{name}`, an environment
 * that takes its own mandatory argument (tabular's column spec, minipage's
 * width) opens its body with that argument — that is why some bodies start with
 * `{...}` rather than a newline.
 */

export type LatexCommand = {
	/** Name without the leading backslash, e.g. "frac". */
	name: string;
	/** Monaco snippet body without the leading backslash, e.g. "frac{$1}{$2}$0". Omit when the command takes no arguments. */
	snippet?: string;
	/** One-line description shown in the completion detail row. */
	detail: string;
	/** Longer markdown documentation, optional. */
	doc?: string;
	/**
	 * A short, realistic usage line, e.g. "\\draw (0,0) -- (2,1);". Rendered as a
	 * fenced `latex` block in the hover card, below `doc` — so it is raw LaTeX,
	 * not markdown, and needs no backticks of its own.
	 */
	example?: string;
	/** Package that provides it. Omit for LaTeX kernel / plain TeX. */
	package?: string;
	/** Where it is valid. Used to filter suggestions. */
	context?: "math" | "text" | "both";
};

export type LatexEnvironment = {
	name: string;
	detail: string;
	/** Snippet body for the environment's INNER content, e.g. for itemize: "\n\t\\item $0\n". Optional. */
	body?: string;
	package?: string;
	context?: "math" | "text" | "both";
};

export type LatexPackage = { name: string; detail: string };
export type LatexClass = { name: string; detail: string };

/* ------------------------------------------------------------------ commands */

export const LATEX_COMMANDS: readonly LatexCommand[] = [
	/* --- sectioning ------------------------------------------------------ */
	{
		name: "part",
		snippet: "part{$1}$0",
		detail: "Top-level division",
		doc: "Starred form `\\part*{…}` is unnumbered and omitted from the table of contents.",
		context: "text",
	},
	{
		name: "chapter",
		snippet: "chapter{$1}$0",
		detail: "Chapter heading (book/report only)",
		doc: "Not available in `article`. `\\chapter*{…}` is unnumbered; the optional argument sets a shorter ToC entry.",
		context: "text",
	},
	{
		name: "section",
		snippet: "section{$1}$0",
		detail: "Section heading",
		doc: "`\\section*{…}` is unnumbered and does not appear in the table of contents.",
		context: "text",
	},
	{
		name: "subsection",
		snippet: "subsection{$1}$0",
		detail: "Subsection heading",
		context: "text",
	},
	{
		name: "subsubsection",
		snippet: "subsubsection{$1}$0",
		detail: "Sub-subsection heading",
		doc: "Numbered only up to `secnumdepth`; in `article` it is unnumbered by default.",
		context: "text",
	},
	{
		name: "paragraph",
		snippet: "paragraph{$1}$0",
		detail: "Run-in paragraph heading",
		context: "text",
	},
	{
		name: "subparagraph",
		snippet: "subparagraph{$1}$0",
		detail: "Run-in sub-paragraph heading",
		context: "text",
	},

	/* --- document structure ---------------------------------------------- */
	{
		name: "documentclass",
		snippet: "documentclass[${1:11pt}]{${2:article}}$0",
		detail: "Select the document class",
		doc: "The first command of every document. Options set base font size, paper and one/two-column layout.",
	},
	{
		name: "usepackage",
		snippet: "usepackage{$1}$0",
		detail: "Load a package",
		doc: "Preamble only. Options go in the optional argument: `\\usepackage[utf8]{inputenc}`.",
	},
	{
		name: "RequirePackage",
		snippet: "RequirePackage{$1}$0",
		detail: "Load a package from a class or package file",
	},
	{ name: "begin", snippet: "begin{$1}\n\t$0\n\\end{$1}", detail: "Open an environment" },
	{ name: "end", snippet: "end{$1}$0", detail: "Close an environment" },
	{ name: "title", snippet: "title{$1}$0", detail: "Document title", context: "text" },
	{ name: "author", snippet: "author{$1}$0", detail: "Document author(s)", context: "text" },
	{
		name: "date",
		snippet: "date{$1}$0",
		detail: "Document date",
		doc: "`\\date{}` suppresses the date entirely; omitting it uses `\\today`.",
		context: "text",
	},
	{ name: "thanks", snippet: "thanks{$1}$0", detail: "Title-block footnote", context: "text" },
	{ name: "maketitle", detail: "Typeset the title block", context: "text" },
	{ name: "tableofcontents", detail: "Insert the table of contents", context: "text" },
	{ name: "listoffigures", detail: "Insert the list of figures", context: "text" },
	{ name: "listoftables", detail: "Insert the list of tables", context: "text" },
	{
		name: "appendix",
		detail: "Switch following sections to appendix numbering",
		doc: "A switch, not an environment — everything after it is an appendix.",
		context: "text",
	},
	{ name: "frontmatter", detail: "Begin front matter (book)", context: "text" },
	{ name: "mainmatter", detail: "Begin main matter, restart arabic page numbers (book)", context: "text" },
	{ name: "backmatter", detail: "Begin back matter (book)", context: "text" },
	{
		name: "bibliography",
		snippet: "bibliography{$1}$0",
		detail: "BibTeX database file (without .bib)",
		context: "text",
	},
	{
		name: "bibliographystyle",
		snippet: "bibliographystyle{${1:plain}}$0",
		detail: "BibTeX bibliography style",
		context: "text",
	},
	{
		name: "addbibresource",
		snippet: "addbibresource{${1:refs.bib}}$0",
		detail: "Register a .bib file (biblatex)",
		package: "biblatex",
	},
	{
		name: "printbibliography",
		detail: "Typeset the bibliography (biblatex)",
		package: "biblatex",
		context: "text",
	},
	{
		name: "input",
		snippet: "input{$1}$0",
		detail: "Inline another file verbatim",
		doc: "Unlike `\\include` it starts no new page and may be nested.",
	},
	{
		name: "include",
		snippet: "include{$1}$0",
		detail: "Include a file on a new page",
		doc: "Works with `\\includeonly` to compile a subset while keeping cross-references and page numbers.",
	},
	{
		name: "includeonly",
		snippet: "includeonly{$1}$0",
		detail: "Restrict which \\include files are processed",
	},
	{ name: "today", detail: "Current date", context: "text" },
	{ name: "LaTeX", detail: "The LaTeX logo", context: "text" },
	{ name: "TeX", detail: "The TeX logo", context: "text" },
	{ name: "LaTeXe", detail: "The LaTeX2e logo", context: "text" },

	/* --- text formatting -------------------------------------------------- */
	{ name: "textbf", snippet: "textbf{$1}$0", detail: "Bold text", context: "text" },
	{ name: "textit", snippet: "textit{$1}$0", detail: "Italic text", context: "text" },
	{ name: "texttt", snippet: "texttt{$1}$0", detail: "Monospace (typewriter) text", context: "text" },
	{ name: "textsf", snippet: "textsf{$1}$0", detail: "Sans-serif text", context: "text" },
	{ name: "textrm", snippet: "textrm{$1}$0", detail: "Roman (serif) text", context: "text" },
	{ name: "textsc", snippet: "textsc{$1}$0", detail: "Small capitals", context: "text" },
	{ name: "textsl", snippet: "textsl{$1}$0", detail: "Slanted text", context: "text" },
	{ name: "textmd", snippet: "textmd{$1}$0", detail: "Medium weight text", context: "text" },
	{ name: "textup", snippet: "textup{$1}$0", detail: "Upright shape text", context: "text" },
	{ name: "textnormal", snippet: "textnormal{$1}$0", detail: "Reset to the document body font", context: "text" },
	{
		name: "emph",
		snippet: "emph{$1}$0",
		detail: "Emphasis (nests: italic, then upright)",
		doc: "Prefer this over `\\textit` for semantic emphasis — it flips shape when nested.",
		context: "text",
	},
	{
		name: "underline",
		snippet: "underline{$1}$0",
		detail: "Underline (text) / overline's counterpart (math)",
		doc: "In text mode the content cannot break across lines; `soul`'s `\\ul` is usually better.",
		context: "both",
	},
	{ name: "textsuperscript", snippet: "textsuperscript{$1}$0", detail: "Superscript in text mode", context: "text" },
	{ name: "textsubscript", snippet: "textsubscript{$1}$0", detail: "Subscript in text mode", context: "text" },
	{ name: "textbackslash", detail: "A literal backslash", context: "text" },
	{ name: "textasciitilde", detail: "A literal tilde", context: "text" },
	{ name: "textasciicircum", detail: "A literal caret", context: "text" },
	{ name: "textellipsis", detail: "Text-mode ellipsis", context: "text" },
	{ name: "textquotedblleft", detail: "Opening double quote", context: "text" },
	{ name: "textquotedblright", detail: "Closing double quote", context: "text" },
	{ name: "verb", snippet: "verb|$1|$0", detail: "Inline verbatim between matching delimiters", context: "text" },
	{ name: "bfseries", detail: "Switch to bold until the group ends", context: "text" },
	{ name: "itshape", detail: "Switch to italic until the group ends", context: "text" },
	{ name: "ttfamily", detail: "Switch to monospace until the group ends", context: "text" },
	{ name: "sffamily", detail: "Switch to sans-serif until the group ends", context: "text" },
	{ name: "rmfamily", detail: "Switch to roman until the group ends", context: "text" },
	{ name: "scshape", detail: "Switch to small caps until the group ends", context: "text" },
	{ name: "normalfont", detail: "Reset all font attributes", context: "text" },

	/* --- font sizes -------------------------------------------------------- */
	{ name: "tiny", detail: "Font size: tiny", context: "text" },
	{ name: "scriptsize", detail: "Font size: script", context: "text" },
	{ name: "footnotesize", detail: "Font size: footnote", context: "text" },
	{ name: "small", detail: "Font size: small", context: "text" },
	{ name: "normalsize", detail: "Font size: document default", context: "text" },
	{ name: "large", detail: "Font size: large", context: "text" },
	{ name: "Large", detail: "Font size: larger", context: "text" },
	{ name: "LARGE", detail: "Font size: even larger", context: "text" },
	{ name: "huge", detail: "Font size: huge", context: "text" },
	{ name: "Huge", detail: "Font size: largest", context: "text" },

	/* --- colour and boxes --------------------------------------------------- */
	{
		name: "textcolor",
		snippet: "textcolor{${1:red}}{$2}$0",
		detail: "Set the colour of a piece of text",
		package: "xcolor",
		context: "both",
	},
	{ name: "color", snippet: "color{${1:red}}$0", detail: "Switch colour until the group ends", package: "xcolor" },
	{
		name: "colorbox",
		snippet: "colorbox{${1:yellow}}{$2}$0",
		detail: "Box with a coloured background",
		package: "xcolor",
		context: "text",
	},
	{
		name: "definecolor",
		snippet: "definecolor{$1}{${2:HTML}}{$3}$0",
		detail: "Define a named colour",
		package: "xcolor",
	},
	{ name: "mbox", snippet: "mbox{$1}$0", detail: "Unbreakable horizontal box", context: "both" },
	{ name: "fbox", snippet: "fbox{$1}$0", detail: "Framed box", context: "both" },
	{ name: "framebox", snippet: "framebox[${1:width}]{$2}$0", detail: "Framed box of a given width", context: "both" },
	{ name: "makebox", snippet: "makebox[${1:width}]{$2}$0", detail: "Box of a given width", context: "both" },
	{
		name: "parbox",
		snippet: "parbox{${1:\\linewidth}}{$2}$0",
		detail: "Paragraph box of a given width",
		context: "text",
	},
	{ name: "raisebox", snippet: "raisebox{${1:1ex}}{$2}$0", detail: "Shift a box vertically", context: "both" },
	{ name: "rule", snippet: "rule{${1:\\linewidth}}{${2:0.4pt}}$0", detail: "Solid rectangular rule", context: "both" },

	/* --- references and citations ------------------------------------------- */
	{ name: "label", snippet: "label{${1:sec:}}$0", detail: "Attach a cross-reference key", context: "both" },
	{ name: "ref", snippet: "ref{$1}$0", detail: "Reference a label's number", context: "both" },
	{
		name: "eqref",
		snippet: "eqref{$1}$0",
		detail: "Reference an equation, with parentheses",
		package: "amsmath",
		context: "both",
	},
	{ name: "pageref", snippet: "pageref{$1}$0", detail: "Page number of a label", context: "both" },
	{
		name: "autoref",
		snippet: "autoref{$1}$0",
		detail: "Reference with an automatic type prefix",
		package: "hyperref",
		context: "both",
	},
	{
		name: "cref",
		snippet: "cref{$1}$0",
		detail: "Clever reference — type prefix, ranges, lists",
		package: "cleveref",
		context: "both",
	},
	{
		name: "Cref",
		snippet: "Cref{$1}$0",
		detail: "Clever reference, capitalised (sentence start)",
		package: "cleveref",
		context: "both",
	},
	{
		name: "nameref",
		snippet: "nameref{$1}$0",
		detail: "Reference a section by its title",
		package: "hyperref",
		context: "both",
	},
	{ name: "cite", snippet: "cite{$1}$0", detail: "Cite a bibliography entry", context: "text" },
	{
		name: "citep",
		snippet: "citep{$1}$0",
		detail: "Parenthetical citation (Author, year)",
		package: "natbib",
		context: "text",
	},
	{
		name: "citet",
		snippet: "citet{$1}$0",
		detail: "Textual citation — Author (year)",
		package: "natbib",
		context: "text",
	},
	{ name: "citeauthor", snippet: "citeauthor{$1}$0", detail: "Cite the author name only", package: "natbib", context: "text" },
	{ name: "citeyear", snippet: "citeyear{$1}$0", detail: "Cite the year only", package: "natbib", context: "text" },
	{ name: "textcite", snippet: "textcite{$1}$0", detail: "Textual citation (biblatex)", package: "biblatex", context: "text" },
	{ name: "parencite", snippet: "parencite{$1}$0", detail: "Parenthetical citation (biblatex)", package: "biblatex", context: "text" },
	{ name: "nocite", snippet: "nocite{$1}$0", detail: "Include an entry without citing it", context: "text" },
	{ name: "footnote", snippet: "footnote{$1}$0", detail: "Footnote at the bottom of the page", context: "text" },
	{
		name: "footnotemark",
		detail: "Footnote marker without the text",
		doc: "Pair with `\\footnotetext` when the note cannot be placed where the mark belongs (tables, minipages).",
		context: "text",
	},
	{ name: "footnotetext", snippet: "footnotetext{$1}$0", detail: "Footnote text for a separate mark", context: "text" },
	{ name: "marginpar", snippet: "marginpar{$1}$0", detail: "Margin note", context: "text" },
	{ name: "url", snippet: "url{$1}$0", detail: "Typeset a URL, breakable", package: "url", context: "text" },
	{ name: "href", snippet: "href{${1:url}}{${2:text}}$0", detail: "Hyperlink with display text", package: "hyperref", context: "text" },
	{ name: "index", snippet: "index{$1}$0", detail: "Add an index entry", package: "makeidx", context: "text" },
	{ name: "glossary", snippet: "glossary{$1}$0", detail: "Add a glossary entry", context: "text" },

	/* --- math: structure ---------------------------------------------------- */
	{ name: "frac", snippet: "frac{$1}{$2}$0", detail: "Fraction", context: "math" },
	{ name: "dfrac", snippet: "dfrac{$1}{$2}$0", detail: "Display-style fraction", package: "amsmath", context: "math" },
	{ name: "tfrac", snippet: "tfrac{$1}{$2}$0", detail: "Text-style (small) fraction", package: "amsmath", context: "math" },
	{ name: "cfrac", snippet: "cfrac{$1}{$2}$0", detail: "Continued fraction", package: "amsmath", context: "math" },
	{ name: "binom", snippet: "binom{$1}{$2}$0", detail: "Binomial coefficient", package: "amsmath", context: "math" },
	{
		name: "sqrt",
		snippet: "sqrt{$1}$0",
		detail: "Square root",
		doc: "`\\sqrt[3]{x}` gives the cube root.",
		context: "math",
	},
	{ name: "sum", detail: "Summation operator", context: "math" },
	{ name: "prod", detail: "Product operator", context: "math" },
	{ name: "coprod", detail: "Coproduct operator", context: "math" },
	{ name: "int", detail: "Integral", context: "math" },
	{ name: "iint", detail: "Double integral", package: "amsmath", context: "math" },
	{ name: "iiint", detail: "Triple integral", package: "amsmath", context: "math" },
	{ name: "oint", detail: "Contour integral", context: "math" },
	{ name: "bigcup", detail: "Big union operator", context: "math" },
	{ name: "bigcap", detail: "Big intersection operator", context: "math" },
	{ name: "bigoplus", detail: "Big direct-sum operator", context: "math" },
	{ name: "bigotimes", detail: "Big tensor-product operator", context: "math" },
	{ name: "lim", detail: "Limit operator", context: "math" },
	{ name: "limsup", detail: "Limit superior", context: "math" },
	{ name: "liminf", detail: "Limit inferior", context: "math" },
	{
		name: "left",
		snippet: "left($1\\right)$0",
		detail: "Auto-sized opening delimiter",
		doc: "Every `\\left` needs a matching `\\right`; use `\\right.` for an invisible one.",
		context: "math",
	},
	{ name: "right", detail: "Auto-sized closing delimiter", context: "math" },
	{ name: "big", detail: "Delimiter one size up", context: "math" },
	{ name: "Big", detail: "Delimiter two sizes up", context: "math" },
	{ name: "bigg", detail: "Delimiter three sizes up", context: "math" },
	{ name: "Bigg", detail: "Delimiter four sizes up", context: "math" },
	{ name: "langle", detail: "Left angle bracket", context: "math" },
	{ name: "rangle", detail: "Right angle bracket", context: "math" },
	{ name: "lfloor", detail: "Left floor bracket", context: "math" },
	{ name: "rfloor", detail: "Right floor bracket", context: "math" },
	{ name: "lceil", detail: "Left ceiling bracket", context: "math" },
	{ name: "rceil", detail: "Right ceiling bracket", context: "math" },
	{ name: "text", snippet: "text{$1}$0", detail: "Upright text inside math", package: "amsmath", context: "math" },
	{
		name: "operatorname",
		snippet: "operatorname{$1}$0",
		detail: "Typeset a one-off operator name",
		package: "amsmath",
		context: "math",
	},
	{ name: "substack", snippet: "substack{$1 \\\\ $2}$0", detail: "Multi-line limits under an operator", package: "amsmath", context: "math" },
	{ name: "stackrel", snippet: "stackrel{$1}{$2}$0", detail: "Stack a symbol above a relation", context: "math" },
	{ name: "boxed", snippet: "boxed{$1}$0", detail: "Draw a box around a formula", package: "amsmath", context: "math" },
	{ name: "intertext", snippet: "intertext{$1}$0", detail: "Insert a line of text inside a display", package: "amsmath", context: "math" },
	{ name: "nonumber", detail: "Suppress the number of this equation line", context: "math" },
	{ name: "notag", detail: "Suppress the number of this equation line (amsmath)", package: "amsmath", context: "math" },
	{ name: "displaystyle", detail: "Force display-size math", context: "math" },
	{ name: "textstyle", detail: "Force inline-size math", context: "math" },
	{ name: "scriptstyle", detail: "Force script-size math", context: "math" },

	/* --- math: accents and alphabets --------------------------------------- */
	{ name: "overline", snippet: "overline{$1}$0", detail: "Line above", context: "math" },
	{ name: "hat", snippet: "hat{$1}$0", detail: "Hat accent", context: "math" },
	{ name: "widehat", snippet: "widehat{$1}$0", detail: "Wide hat accent", context: "math" },
	{ name: "bar", snippet: "bar{$1}$0", detail: "Bar accent", context: "math" },
	{ name: "vec", snippet: "vec{$1}$0", detail: "Vector arrow accent", context: "math" },
	{ name: "tilde", snippet: "tilde{$1}$0", detail: "Tilde accent", context: "math" },
	{ name: "widetilde", snippet: "widetilde{$1}$0", detail: "Wide tilde accent", context: "math" },
	{ name: "dot", snippet: "dot{$1}$0", detail: "Single dot accent", context: "math" },
	{ name: "ddot", snippet: "ddot{$1}$0", detail: "Double dot accent", context: "math" },
	{ name: "overbrace", snippet: "overbrace{$1}$0", detail: "Brace above, with optional superscript label", context: "math" },
	{ name: "underbrace", snippet: "underbrace{$1}$0", detail: "Brace below, with optional subscript label", context: "math" },
	{ name: "overrightarrow", snippet: "overrightarrow{$1}$0", detail: "Right arrow above", context: "math" },
	{ name: "mathbb", snippet: "mathbb{$1}$0", detail: "Blackboard bold — number sets", package: "amssymb", context: "math" },
	{ name: "mathcal", snippet: "mathcal{$1}$0", detail: "Calligraphic capitals", context: "math" },
	{ name: "mathfrak", snippet: "mathfrak{$1}$0", detail: "Fraktur letters", package: "amssymb", context: "math" },
	{ name: "mathbf", snippet: "mathbf{$1}$0", detail: "Bold math", context: "math" },
	{ name: "mathit", snippet: "mathit{$1}$0", detail: "Italic math", context: "math" },
	{ name: "mathrm", snippet: "mathrm{$1}$0", detail: "Upright roman math", context: "math" },
	{ name: "mathsf", snippet: "mathsf{$1}$0", detail: "Sans-serif math", context: "math" },
	{ name: "mathtt", snippet: "mathtt{$1}$0", detail: "Monospace math", context: "math" },
	{ name: "bm", snippet: "bm{$1}$0", detail: "Bold math, including symbols", package: "bm", context: "math" },

	/* --- math: symbols ------------------------------------------------------ */
	{ name: "infty", detail: "Infinity", context: "math" },
	{ name: "partial", detail: "Partial derivative sign", context: "math" },
	{ name: "nabla", detail: "Nabla / del operator", context: "math" },
	{ name: "cdot", detail: "Centred dot (multiplication)", context: "math" },
	{ name: "cdots", detail: "Centred ellipsis", context: "math" },
	{ name: "ldots", detail: "Baseline ellipsis", context: "both" },
	{ name: "vdots", detail: "Vertical ellipsis", context: "math" },
	{ name: "ddots", detail: "Diagonal ellipsis", context: "math" },
	{ name: "times", detail: "Multiplication cross", context: "math" },
	{ name: "div", detail: "Division sign", context: "math" },
	{ name: "pm", detail: "Plus-minus", context: "math" },
	{ name: "mp", detail: "Minus-plus", context: "math" },
	{ name: "ast", detail: "Asterisk operator", context: "math" },
	{ name: "star", detail: "Star operator", context: "math" },
	{ name: "circ", detail: "Composition ring", context: "math" },
	{ name: "bullet", detail: "Bullet operator", context: "math" },
	{ name: "oplus", detail: "Direct sum", context: "math" },
	{ name: "ominus", detail: "Circled minus", context: "math" },
	{ name: "otimes", detail: "Tensor product", context: "math" },
	{ name: "oslash", detail: "Circled slash", context: "math" },
	{ name: "leq", detail: "Less than or equal", context: "math" },
	{ name: "geq", detail: "Greater than or equal", context: "math" },
	{ name: "neq", detail: "Not equal", context: "math" },
	{ name: "ll", detail: "Much less than", context: "math" },
	{ name: "gg", detail: "Much greater than", context: "math" },
	{ name: "approx", detail: "Approximately equal", context: "math" },
	{ name: "equiv", detail: "Equivalent / congruent modulo", context: "math" },
	{ name: "sim", detail: "Similar to", context: "math" },
	{ name: "simeq", detail: "Asymptotically equal", context: "math" },
	{ name: "cong", detail: "Congruent to", context: "math" },
	{ name: "propto", detail: "Proportional to", context: "math" },
	{ name: "subset", detail: "Proper subset", context: "math" },
	{ name: "subseteq", detail: "Subset or equal", context: "math" },
	{ name: "supset", detail: "Proper superset", context: "math" },
	{ name: "supseteq", detail: "Superset or equal", context: "math" },
	{ name: "in", detail: "Element of", context: "math" },
	{ name: "notin", detail: "Not an element of", context: "math" },
	{ name: "ni", detail: "Contains as element", context: "math" },
	{ name: "cup", detail: "Union", context: "math" },
	{ name: "cap", detail: "Intersection", context: "math" },
	{ name: "setminus", detail: "Set difference", context: "math" },
	{ name: "emptyset", detail: "Empty set", context: "math" },
	{ name: "varnothing", detail: "Empty set (slashed circle)", package: "amssymb", context: "math" },
	{ name: "forall", detail: "Universal quantifier", context: "math" },
	{ name: "exists", detail: "Existential quantifier", context: "math" },
	{ name: "nexists", detail: "Does not exist", package: "amssymb", context: "math" },
	{ name: "neg", detail: "Logical negation", context: "math" },
	{ name: "land", detail: "Logical and", context: "math" },
	{ name: "lor", detail: "Logical or", context: "math" },
	{ name: "perp", detail: "Perpendicular", context: "math" },
	{ name: "parallel", detail: "Parallel to", context: "math" },
	{ name: "angle", detail: "Angle sign", context: "math" },
	{ name: "triangle", detail: "Triangle", context: "math" },
	{ name: "prime", detail: "Prime mark", context: "math" },
	{ name: "aleph", detail: "Aleph", context: "math" },
	{ name: "hbar", detail: "Reduced Planck constant", context: "math" },
	{ name: "ell", detail: "Script small l", context: "math" },
	{ name: "Re", detail: "Real part", context: "math" },
	{ name: "Im", detail: "Imaginary part", context: "math" },
	{ name: "rightarrow", detail: "Right arrow", context: "math" },
	{ name: "leftarrow", detail: "Left arrow", context: "math" },
	{ name: "Rightarrow", detail: "Double right arrow (implies)", context: "math" },
	{ name: "Leftarrow", detail: "Double left arrow", context: "math" },
	{ name: "leftrightarrow", detail: "Left-right arrow", context: "math" },
	{ name: "Leftrightarrow", detail: "Double left-right arrow (iff)", context: "math" },
	{ name: "longrightarrow", detail: "Long right arrow", context: "math" },
	{ name: "longleftarrow", detail: "Long left arrow", context: "math" },
	{ name: "mapsto", detail: "Maps-to arrow", context: "math" },
	{ name: "to", detail: "Right arrow (short form)", context: "math" },
	{ name: "gets", detail: "Left arrow (short form)", context: "math" },
	{ name: "implies", detail: "Implies, with wide spacing", package: "amsmath", context: "math" },
	{ name: "iff", detail: "If and only if, with wide spacing", package: "amsmath", context: "math" },

	/* --- Greek: lowercase --------------------------------------------------- */
	{ name: "alpha", detail: "Greek small letter alpha", context: "math" },
	{ name: "beta", detail: "Greek small letter beta", context: "math" },
	{ name: "gamma", detail: "Greek small letter gamma", context: "math" },
	{ name: "delta", detail: "Greek small letter delta", context: "math" },
	{ name: "epsilon", detail: "Greek small letter epsilon (lunate)", context: "math" },
	{ name: "varepsilon", detail: "Greek small letter epsilon (variant)", context: "math" },
	{ name: "zeta", detail: "Greek small letter zeta", context: "math" },
	{ name: "eta", detail: "Greek small letter eta", context: "math" },
	{ name: "theta", detail: "Greek small letter theta", context: "math" },
	{ name: "vartheta", detail: "Greek small letter theta (variant)", context: "math" },
	{ name: "iota", detail: "Greek small letter iota", context: "math" },
	{ name: "kappa", detail: "Greek small letter kappa", context: "math" },
	{ name: "lambda", detail: "Greek small letter lambda", context: "math" },
	{ name: "mu", detail: "Greek small letter mu", context: "math" },
	{ name: "nu", detail: "Greek small letter nu", context: "math" },
	{ name: "xi", detail: "Greek small letter xi", context: "math" },
	{ name: "pi", detail: "Greek small letter pi", context: "math" },
	{ name: "varpi", detail: "Greek small letter pi (variant)", context: "math" },
	{ name: "rho", detail: "Greek small letter rho", context: "math" },
	{ name: "varrho", detail: "Greek small letter rho (variant)", context: "math" },
	{ name: "sigma", detail: "Greek small letter sigma", context: "math" },
	{ name: "varsigma", detail: "Greek small letter sigma (final form)", context: "math" },
	{ name: "tau", detail: "Greek small letter tau", context: "math" },
	{ name: "upsilon", detail: "Greek small letter upsilon", context: "math" },
	{ name: "phi", detail: "Greek small letter phi", context: "math" },
	{ name: "varphi", detail: "Greek small letter phi (variant)", context: "math" },
	{ name: "chi", detail: "Greek small letter chi", context: "math" },
	{ name: "psi", detail: "Greek small letter psi", context: "math" },
	{ name: "omega", detail: "Greek small letter omega", context: "math" },

	/* --- Greek: uppercase --------------------------------------------------- */
	{ name: "Gamma", detail: "Greek capital letter gamma", context: "math" },
	{ name: "Delta", detail: "Greek capital letter delta", context: "math" },
	{ name: "Theta", detail: "Greek capital letter theta", context: "math" },
	{ name: "Lambda", detail: "Greek capital letter lambda", context: "math" },
	{ name: "Xi", detail: "Greek capital letter xi", context: "math" },
	{ name: "Pi", detail: "Greek capital letter pi", context: "math" },
	{ name: "Sigma", detail: "Greek capital letter sigma", context: "math" },
	{ name: "Upsilon", detail: "Greek capital letter upsilon", context: "math" },
	{ name: "Phi", detail: "Greek capital letter phi", context: "math" },
	{ name: "Psi", detail: "Greek capital letter psi", context: "math" },
	{ name: "Omega", detail: "Greek capital letter omega", context: "math" },

	/* --- math operators (upright, log-like) -------------------------------- */
	{ name: "sin", detail: "Sine", context: "math" },
	{ name: "cos", detail: "Cosine", context: "math" },
	{ name: "tan", detail: "Tangent", context: "math" },
	{ name: "cot", detail: "Cotangent", context: "math" },
	{ name: "sec", detail: "Secant", context: "math" },
	{ name: "csc", detail: "Cosecant", context: "math" },
	{ name: "arcsin", detail: "Inverse sine", context: "math" },
	{ name: "arccos", detail: "Inverse cosine", context: "math" },
	{ name: "arctan", detail: "Inverse tangent", context: "math" },
	{ name: "sinh", detail: "Hyperbolic sine", context: "math" },
	{ name: "cosh", detail: "Hyperbolic cosine", context: "math" },
	{ name: "tanh", detail: "Hyperbolic tangent", context: "math" },
	{ name: "log", detail: "Logarithm", context: "math" },
	{ name: "ln", detail: "Natural logarithm", context: "math" },
	{ name: "exp", detail: "Exponential function", context: "math" },
	{ name: "min", detail: "Minimum", context: "math" },
	{ name: "max", detail: "Maximum", context: "math" },
	{ name: "sup", detail: "Supremum", context: "math" },
	{ name: "inf", detail: "Infimum", context: "math" },
	{ name: "det", detail: "Determinant", context: "math" },
	{ name: "dim", detail: "Dimension", context: "math" },
	{ name: "ker", detail: "Kernel", context: "math" },
	{ name: "deg", detail: "Degree", context: "math" },
	{ name: "gcd", detail: "Greatest common divisor", context: "math" },
	{ name: "arg", detail: "Argument", context: "math" },
	{ name: "Pr", detail: "Probability", context: "math" },
	{ name: "bmod", detail: "Binary modulo operator", context: "math" },
	{ name: "pmod", snippet: "pmod{$1}$0", detail: "Parenthesised modulo", context: "math" },

	/* --- tables, figures, lists --------------------------------------------- */
	{
		name: "caption",
		snippet: "caption{$1}$0",
		detail: "Caption for a figure or table",
		doc: "Put `\\label` *after* `\\caption` — the label picks up the caption's counter.",
		context: "text",
	},
	{ name: "centering", detail: "Centre everything to the end of the group", context: "text" },
	{ name: "raggedright", detail: "Left-align, ragged right edge", context: "text" },
	{ name: "raggedleft", detail: "Right-align, ragged left edge", context: "text" },
	{
		name: "includegraphics",
		snippet: "includegraphics[width=${1:0.8\\textwidth}]{$2}$0",
		detail: "Insert an image",
		doc: "Give the filename without an extension so the driver can pick the best available format.",
		package: "graphicx",
		context: "text",
	},
	{ name: "graphicspath", snippet: "graphicspath{{${1:figures/}}}$0", detail: "Directories searched for images", package: "graphicx" },
	{ name: "hline", detail: "Full-width horizontal rule in a table", context: "text" },
	{ name: "cline", snippet: "cline{${1:2-3}}$0", detail: "Partial horizontal rule spanning columns", context: "text" },
	{ name: "toprule", detail: "Top rule of a formal table", package: "booktabs", context: "text" },
	{ name: "midrule", detail: "Middle rule of a formal table", package: "booktabs", context: "text" },
	{ name: "bottomrule", detail: "Bottom rule of a formal table", package: "booktabs", context: "text" },
	{ name: "cmidrule", snippet: "cmidrule(lr){${1:2-3}}$0", detail: "Partial rule for a formal table", package: "booktabs", context: "text" },
	{
		name: "multicolumn",
		snippet: "multicolumn{${1:2}}{${2:c}}{$3}$0",
		detail: "Cell spanning several columns",
		context: "text",
	},
	{
		name: "multirow",
		snippet: "multirow{${1:2}}{${2:*}}{$3}$0",
		detail: "Cell spanning several rows",
		package: "multirow",
		context: "text",
	},
	{ name: "item", snippet: "item $0", detail: "List item", doc: "In `description`, the optional argument is the term: `\\item[Term]`.", context: "text" },
	{ name: "setlist", snippet: "setlist[${1:itemize}]{$2}$0", detail: "Configure list spacing and labels", package: "enumitem" },
	{ name: "arraybackslash", detail: "Restore \\\\ inside a ragged array column", package: "array", context: "text" },
	{ name: "tabcolsep", detail: "Half the horizontal space between table columns (length)", context: "text" },
	{ name: "arraystretch", detail: "Row-height multiplier for tables (redefine with \\renewcommand)", context: "text" },

	/* --- definitions --------------------------------------------------------- */
	{
		name: "newcommand",
		snippet: "newcommand{\\$1}[${2:1}]{$3}$0",
		detail: "Define a new command",
		doc: "Errors if the name already exists — that check is the point; use `\\renewcommand` to override.",
	},
	{ name: "renewcommand", snippet: "renewcommand{\\$1}{$2}$0", detail: "Redefine an existing command" },
	{ name: "providecommand", snippet: "providecommand{\\$1}{$2}$0", detail: "Define a command only if it does not exist" },
	{
		name: "newenvironment",
		snippet: "newenvironment{$1}{${2:begin code}}{${3:end code}}$0",
		detail: "Define a new environment",
	},
	{ name: "renewenvironment", snippet: "renewenvironment{$1}{$2}{$3}$0", detail: "Redefine an existing environment" },
	{
		name: "newtheorem",
		snippet: "newtheorem{${1:theorem}}{${2:Theorem}}[${3:section}]$0",
		detail: "Declare a theorem-like environment",
		package: "amsthm",
	},
	{
		name: "DeclareMathOperator",
		snippet: "DeclareMathOperator{\\$1}{$2}$0",
		detail: "Declare an upright math operator",
		doc: "The starred form makes an operator that takes limits, like `\\lim`.",
		package: "amsmath",
	},
	{ name: "setlength", snippet: "setlength{\\${1:parindent}}{${2:0pt}}$0", detail: "Set a length to a value" },
	{ name: "addtolength", snippet: "addtolength{\\$1}{$2}$0", detail: "Add to a length" },
	{ name: "newlength", snippet: "newlength{\\$1}$0", detail: "Allocate a new length register" },
	{ name: "newcounter", snippet: "newcounter{$1}$0", detail: "Allocate a new counter" },
	{ name: "setcounter", snippet: "setcounter{$1}{${2:0}}$0", detail: "Set a counter's value" },
	{ name: "stepcounter", snippet: "stepcounter{$1}$0", detail: "Increment a counter and reset its children" },
	{ name: "addtocounter", snippet: "addtocounter{$1}{${2:1}}$0", detail: "Add to a counter" },
	{ name: "value", snippet: "value{$1}$0", detail: "The numeric value of a counter" },
	{
		name: "def",
		snippet: "def\\$1{$2}$0",
		detail: "Plain TeX definition (no existence check)",
		doc: "Prefer `\\newcommand` in LaTeX — `\\def` silently clobbers whatever was there.",
	},
	{ name: "let", snippet: "let\\$1=\\$2$0", detail: "Bind one control sequence to another" },
	{ name: "ensuremath", snippet: "ensuremath{$1}$0", detail: "Typeset as math whichever mode we are in" },

	/* --- spacing and breaks --------------------------------------------------- */
	{ name: "newpage", detail: "Start a new page", context: "text" },
	{ name: "clearpage", detail: "New page, flushing pending floats", context: "text" },
	{ name: "cleardoublepage", detail: "New recto page, flushing floats (two-sided)", context: "text" },
	{ name: "pagebreak", detail: "Suggest a page break here", context: "text" },
	{ name: "nopagebreak", detail: "Discourage a page break here", context: "text" },
	{ name: "linebreak", detail: "Break the line, stretching it to the margin", context: "text" },
	{ name: "newline", detail: "Break the line without stretching it", context: "text" },
	{ name: "noindent", detail: "Suppress the indent of this paragraph", context: "text" },
	{ name: "indent", detail: "Force a paragraph indent", context: "text" },
	{ name: "par", detail: "End the current paragraph", context: "text" },
	{ name: "hfill", detail: "Horizontal glue that absorbs all free space", context: "both" },
	{ name: "vfill", detail: "Vertical glue that absorbs all free space", context: "text" },
	{ name: "hrulefill", detail: "Fill horizontally with a rule", context: "text" },
	{ name: "dotfill", detail: "Fill horizontally with dots", context: "text" },
	{ name: "smallskip", detail: "Small vertical space", context: "text" },
	{ name: "medskip", detail: "Medium vertical space", context: "text" },
	{ name: "bigskip", detail: "Large vertical space", context: "text" },
	{ name: "hspace", snippet: "hspace{${1:1em}}$0", detail: "Explicit horizontal space", context: "both" },
	{ name: "vspace", snippet: "vspace{${1:1em}}$0", detail: "Explicit vertical space", context: "text" },
	{ name: "quad", detail: "Space of one em", context: "math" },
	{ name: "qquad", detail: "Space of two ems", context: "math" },
	{ name: "phantom", snippet: "phantom{$1}$0", detail: "Space the size of its (invisible) argument", context: "both" },
	{ name: "vphantom", snippet: "vphantom{$1}$0", detail: "Vertical-only phantom", context: "math" },
	{ name: "hphantom", snippet: "hphantom{$1}$0", detail: "Horizontal-only phantom", context: "math" },

	/* --- page style and layout ------------------------------------------------ */
	{ name: "pagestyle", snippet: "pagestyle{${1:fancy}}$0", detail: "Set the page style for the rest of the document" },
	{ name: "thispagestyle", snippet: "thispagestyle{${1:empty}}$0", detail: "Set the page style for this page only" },
	{ name: "pagenumbering", snippet: "pagenumbering{${1:arabic}}$0", detail: "Choose the page-number format" },
	{ name: "fancyhead", snippet: "fancyhead[${1:L}]{$2}$0", detail: "Set a header field", package: "fancyhdr" },
	{ name: "fancyfoot", snippet: "fancyfoot[${1:C}]{$2}$0", detail: "Set a footer field", package: "fancyhdr" },
	{ name: "geometry", snippet: "geometry{${1:margin=1in}}$0", detail: "Set page geometry after loading", package: "geometry" },
	{ name: "linewidth", detail: "Width of the current line (length)", context: "both" },
	{ name: "textwidth", detail: "Width of the text block (length)", context: "both" },
	{ name: "textheight", detail: "Height of the text block (length)", context: "both" },
	{ name: "columnwidth", detail: "Width of the current column (length)", context: "both" },
	{ name: "onecolumn", detail: "Switch to single-column layout", context: "text" },
	{ name: "twocolumn", detail: "Switch to two-column layout", context: "text" },

	/* --- package-specific odds and ends --------------------------------------- */
	{ name: "lstinline", snippet: "lstinline|$1|$0", detail: "Inline source code", package: "listings", context: "text" },
	{ name: "lstinputlisting", snippet: "lstinputlisting[language=${1:Python}]{$2}$0", detail: "Include a source file as a listing", package: "listings", context: "text" },
	{ name: "lstset", snippet: "lstset{$1}$0", detail: "Configure the listings package", package: "listings" },
	{ name: "mint", snippet: "mint{${1:python}}|$2|$0", detail: "Inline highlighted code", package: "minted", context: "text" },
	{ name: "inputminted", snippet: "inputminted{${1:python}}{$2}$0", detail: "Include a source file, highlighted", package: "minted", context: "text" },
	{ name: "si", snippet: "si{${1:\\metre}}$0", detail: "Typeset a unit", package: "siunitx", context: "both" },
	{ name: "SI", snippet: "SI{$1}{${2:\\metre}}$0", detail: "Typeset a number with a unit (legacy siunitx)", package: "siunitx", context: "both" },
	{ name: "qty", snippet: "qty{$1}{${2:\\metre}}$0", detail: "Typeset a quantity — number and unit", package: "siunitx", context: "both" },
	{ name: "num", snippet: "num{$1}$0", detail: "Typeset a number with consistent formatting", package: "siunitx", context: "both" },
	{ name: "ang", snippet: "ang{$1}$0", detail: "Typeset an angle", package: "siunitx", context: "both" },
	{ name: "todo", snippet: "todo{$1}$0", detail: "Margin to-do note", package: "todonotes", context: "text" },
	{ name: "listoftodos", detail: "List of to-do notes", package: "todonotes", context: "text" },
	{ name: "lipsum", snippet: "lipsum[${1:1-3}]$0", detail: "Filler text for drafting layouts", package: "lipsum", context: "text" },
	{ name: "enquote", snippet: "enquote{$1}$0", detail: "Quotation marks that follow the document language", package: "csquotes", context: "text" },
	{ name: "usetikzlibrary", snippet: "usetikzlibrary{$1}$0", detail: "Load a TikZ library", package: "tikz" },
	{ name: "tikz", snippet: "tikz{$1}$0", detail: "Inline TikZ picture", package: "tikz", context: "text" },
	{ name: "hypersetup", snippet: "hypersetup{${1:colorlinks=true}}$0", detail: "Configure hyperref", package: "hyperref" },
	{ name: "captionsetup", snippet: "captionsetup{$1}$0", detail: "Configure caption formatting", package: "caption" },
	{ name: "titleformat", snippet: "titleformat{\\${1:section}}{$2}{$3}{$4}{$5}$0", detail: "Redefine a heading's appearance", package: "titlesec" },
	{ name: "setstretch", snippet: "setstretch{${1:1.5}}$0", detail: "Set the line-spacing factor", package: "setspace" },
	{ name: "onehalfspacing", detail: "One-and-a-half line spacing", package: "setspace" },
	{ name: "doublespacing", detail: "Double line spacing", package: "setspace" },
	{ name: "selectlanguage", snippet: "selectlanguage{${1:english}}$0", detail: "Switch the document language", package: "babel" },
	{ name: "qedhere", detail: "Place the QED symbol on this line", package: "amsthm", context: "both" },

	/* --- beamer ---------------------------------------------------------------- */
	{ name: "frametitle", snippet: "frametitle{$1}$0", detail: "Title of the current slide", package: "beamer", context: "text" },
	{ name: "framesubtitle", snippet: "framesubtitle{$1}$0", detail: "Subtitle of the current slide", package: "beamer", context: "text" },
	{ name: "usetheme", snippet: "usetheme{${1:default}}$0", detail: "Select a beamer theme", package: "beamer" },
	{ name: "institute", snippet: "institute{$1}$0", detail: "Author's institute in the title block", package: "beamer", context: "text" },
	{ name: "pause", detail: "Split the slide into overlays here", package: "beamer", context: "text" },
	{ name: "titlepage", detail: "Typeset the beamer title slide", package: "beamer", context: "text" },
];

/* -------------------------------------------------------------- environments */

export const LATEX_ENVIRONMENTS: readonly LatexEnvironment[] = [
	{ name: "document", detail: "The document body", body: "\n$0\n" },
	{ name: "abstract", detail: "Abstract", body: "\n\t$0\n", context: "text" },

	/* lists */
	{ name: "itemize", detail: "Bulleted list", body: "\n\t\\item $0\n", context: "text" },
	{ name: "enumerate", detail: "Numbered list", body: "\n\t\\item $0\n", context: "text" },
	{ name: "description", detail: "Labelled list", body: "\n\t\\item[${1:term}] $0\n", context: "text" },
	{ name: "list", detail: "Generic list (the primitive behind the others)", context: "text" },

	/* floats and tables */
	{ name: "figure", detail: "Floating figure", body: "[${1:htbp}]\n\t\\centering\n\t$0\n\t\\caption{}\n\t\\label{fig:}\n", context: "text" },
	{ name: "figure*", detail: "Full-width floating figure (two-column)", body: "[${1:htbp}]\n\t\\centering\n\t$0\n\t\\caption{}\n", context: "text" },
	{ name: "table", detail: "Floating table", body: "[${1:htbp}]\n\t\\centering\n\t$0\n\t\\caption{}\n\t\\label{tab:}\n", context: "text" },
	{ name: "table*", detail: "Full-width floating table (two-column)", body: "[${1:htbp}]\n\t\\centering\n\t$0\n\t\\caption{}\n", context: "text" },
	{ name: "tabular", detail: "Table body with a column specification", body: "{${1:lcr}}\n\t$0\n", context: "text" },
	{ name: "tabular*", detail: "Table body of a fixed total width", body: "{${1:\\linewidth}}{${2:lcr}}\n\t$0\n", context: "text" },
	{ name: "tabularx", detail: "Table with X columns that share the leftover width", body: "{${1:\\linewidth}}{${2:lX}}\n\t$0\n", package: "tabularx", context: "text" },
	{ name: "longtable", detail: "Table that breaks across pages", body: "{${1:lcr}}\n\t$0\n", package: "longtable", context: "text" },
	{ name: "subfigure", detail: "Sub-figure inside a figure", package: "subcaption", context: "text" },
	{ name: "wrapfigure", detail: "Figure with text wrapped around it", body: "{${1:r}}{${2:0.4\\textwidth}}\n\t\\centering\n\t$0\n", package: "wrapfig", context: "text" },
	{ name: "minipage", detail: "A page within a page", body: "{${1:0.48\\textwidth}}\n\t$0\n", context: "text" },

	/* alignment */
	{ name: "center", detail: "Centred block", body: "\n\t$0\n", context: "text" },
	{ name: "flushleft", detail: "Left-aligned block", body: "\n\t$0\n", context: "text" },
	{ name: "flushright", detail: "Right-aligned block", body: "\n\t$0\n", context: "text" },

	/* quotations and verbatim */
	{ name: "quote", detail: "Short quotation, indented both sides", body: "\n\t$0\n", context: "text" },
	{ name: "quotation", detail: "Long quotation, with paragraph indents", body: "\n\t$0\n", context: "text" },
	{ name: "verse", detail: "Poetry, with hanging indents", body: "\n\t$0\n", context: "text" },
	{ name: "verbatim", detail: "Literal text in monospace", body: "\n$0\n", context: "text" },
	{ name: "lstlisting", detail: "Source code with syntax highlighting", body: "[language=${1:Python}]\n$0\n", package: "listings", context: "text" },
	{ name: "minted", detail: "Source code highlighted by Pygments", body: "{${1:python}}\n$0\n", package: "minted", context: "text" },

	/* math */
	{ name: "equation", detail: "Numbered display equation", body: "\n\t$0\n", package: "amsmath", context: "math" },
	{ name: "equation*", detail: "Unnumbered display equation", body: "\n\t$0\n", package: "amsmath", context: "math" },
	{ name: "displaymath", detail: "Unnumbered display equation (kernel)", body: "\n\t$0\n", context: "math" },
	{ name: "align", detail: "Aligned equations, each numbered", body: "\n\t$0\n", package: "amsmath", context: "math" },
	{ name: "align*", detail: "Aligned equations, unnumbered", body: "\n\t$0\n", package: "amsmath", context: "math" },
	{ name: "alignat", detail: "Aligned equations with explicit column count", body: "{${1:2}}\n\t$0\n", package: "amsmath", context: "math" },
	{ name: "flalign", detail: "Aligned equations pushed to the margins", body: "\n\t$0\n", package: "amsmath", context: "math" },
	{ name: "gather", detail: "Centred equations, each numbered", body: "\n\t$0\n", package: "amsmath", context: "math" },
	{ name: "gather*", detail: "Centred equations, unnumbered", body: "\n\t$0\n", package: "amsmath", context: "math" },
	{ name: "multline", detail: "One long equation broken over lines", body: "\n\t$0\n", package: "amsmath", context: "math" },
	{ name: "multline*", detail: "One long equation broken over lines, unnumbered", body: "\n\t$0\n", package: "amsmath", context: "math" },
	{ name: "split", detail: "Split one numbered equation across lines", body: "\n\t$0\n", package: "amsmath", context: "math" },
	{ name: "aligned", detail: "Alignment block usable inside another display", body: "\n\t$0\n", package: "amsmath", context: "math" },
	{ name: "gathered", detail: "Centred block usable inside another display", body: "\n\t$0\n", package: "amsmath", context: "math" },
	{ name: "cases", detail: "Case distinction with a big brace", body: "\n\t$1 & \\text{if } $2 \\\\\n\t$0\n", package: "amsmath", context: "math" },
	{ name: "subequations", detail: "Number a group of equations 1a, 1b, …", body: "\n\t$0\n", package: "amsmath", context: "math" },
	{ name: "array", detail: "Math-mode table", body: "{${1:cc}}\n\t$0\n", context: "math" },
	{ name: "matrix", detail: "Matrix without delimiters", body: "\n\t$0\n", package: "amsmath", context: "math" },
	{ name: "pmatrix", detail: "Matrix in parentheses", body: "\n\t$0\n", package: "amsmath", context: "math" },
	{ name: "bmatrix", detail: "Matrix in square brackets", body: "\n\t$0\n", package: "amsmath", context: "math" },
	{ name: "Bmatrix", detail: "Matrix in curly braces", body: "\n\t$0\n", package: "amsmath", context: "math" },
	{ name: "vmatrix", detail: "Matrix in single bars (determinant)", body: "\n\t$0\n", package: "amsmath", context: "math" },
	{ name: "Vmatrix", detail: "Matrix in double bars (norm)", body: "\n\t$0\n", package: "amsmath", context: "math" },
	{ name: "smallmatrix", detail: "Inline-sized matrix", body: "\n\t$0\n", package: "amsmath", context: "math" },

	/* theorems */
	{ name: "theorem", detail: "Theorem", body: "\n\t$0\n", package: "amsthm", context: "text" },
	{ name: "lemma", detail: "Lemma", body: "\n\t$0\n", package: "amsthm", context: "text" },
	{ name: "corollary", detail: "Corollary", body: "\n\t$0\n", package: "amsthm", context: "text" },
	{ name: "proposition", detail: "Proposition", body: "\n\t$0\n", package: "amsthm", context: "text" },
	{ name: "definition", detail: "Definition", body: "\n\t$0\n", package: "amsthm", context: "text" },
	{ name: "remark", detail: "Remark", body: "\n\t$0\n", package: "amsthm", context: "text" },
	{ name: "example", detail: "Example", body: "\n\t$0\n", package: "amsthm", context: "text" },
	{ name: "proof", detail: "Proof, ending in a QED symbol", body: "\n\t$0\n", package: "amsthm", context: "text" },

	/* algorithms and drawings */
	{ name: "algorithm", detail: "Floating algorithm", body: "\n\t\\caption{$1}\n\t$0\n", package: "algorithm", context: "text" },
	{ name: "algorithmic", detail: "Algorithm pseudocode body", body: "\n\t$0\n", package: "algorithmicx", context: "text" },
	{ name: "tikzpicture", detail: "TikZ drawing", body: "\n\t$0\n", package: "tikz", context: "text" },
	{ name: "axis", detail: "PGFPlots axis (inside tikzpicture)", body: "\n\t$0\n", package: "pgfplots", context: "text" },
	{ name: "scope", detail: "TikZ scope with local options", body: "\n\t$0\n", package: "tikz", context: "text" },

	/* back matter and beamer */
	{ name: "thebibliography", detail: "Hand-written bibliography", body: "{${1:9}}\n\t\\bibitem{$2} $0\n", context: "text" },
	{ name: "appendices", detail: "Appendix block", body: "\n\t$0\n", package: "appendix", context: "text" },
	{ name: "frame", detail: "A beamer slide", body: "{${1:Title}}\n\t$0\n", package: "beamer", context: "text" },
	{ name: "columns", detail: "Side-by-side columns on a slide", body: "\n\t$0\n", package: "beamer", context: "text" },
	{ name: "column", detail: "One column of a beamer slide", body: "{${1:0.5\\textwidth}}\n\t$0\n", package: "beamer", context: "text" },
	{ name: "block", detail: "Titled box on a slide", body: "{${1:Title}}\n\t$0\n", package: "beamer", context: "text" },
	{ name: "alertblock", detail: "Emphasised box on a slide", body: "{${1:Title}}\n\t$0\n", package: "beamer", context: "text" },
	{ name: "exampleblock", detail: "Example box on a slide", body: "{${1:Title}}\n\t$0\n", package: "beamer", context: "text" },
];

/* -------------------------------------------------------------- packages */

export const LATEX_PACKAGES: readonly LatexPackage[] = [
	/* math */
	{ name: "amsmath", detail: "AMS math environments, \\text, \\DeclareMathOperator" },
	{ name: "amssymb", detail: "Extra AMS math symbols, \\mathbb" },
	{ name: "amsthm", detail: "Theorem environments and the proof environment" },
	{ name: "amsfonts", detail: "AMS math fonts" },
	{ name: "mathtools", detail: "Fixes and extensions on top of amsmath" },
	{ name: "bm", detail: "Bold math symbols" },
	{ name: "physics", detail: "Shorthands for derivatives, brackets and operators" },
	{ name: "cancel", detail: "Strike-through in formulas" },
	{ name: "esint", detail: "Extra integral signs" },
	{ name: "stmaryrd", detail: "Semantics and logic symbols" },
	{ name: "braket", detail: "Dirac bra-ket notation" },
	{ name: "unicode-math", detail: "OpenType math fonts (XeTeX/LuaTeX)" },

	/* graphics and colour */
	{ name: "graphicx", detail: "Include and transform images" },
	{ name: "xcolor", detail: "Colour by name, model or mix" },
	{ name: "tikz", detail: "Draw vector graphics in LaTeX" },
	{ name: "pgfplots", detail: "Plots and charts from data or functions" },
	{ name: "pgfplotstable", detail: "Typeset and process tabular data files" },
	{ name: "tcolorbox", detail: "Coloured, breakable boxes" },
	{ name: "adjustbox", detail: "Scale, clip and trim boxes" },
	{ name: "standalone", detail: "Compile figures alone or embedded" },
	{ name: "svg", detail: "Include SVG files via Inkscape" },
	{ name: "epstopdf", detail: "Convert EPS graphics on the fly" },
	{ name: "transparent", detail: "Transparency in PDF output" },

	/* page layout */
	{ name: "geometry", detail: "Page dimensions and margins" },
	{ name: "fancyhdr", detail: "Custom headers and footers" },
	{ name: "titlesec", detail: "Restyle section headings" },
	{ name: "titletoc", detail: "Restyle the table of contents" },
	{ name: "tocloft", detail: "Fine control of the ToC/LoF/LoT" },
	{ name: "setspace", detail: "Line spacing (1.5, double, custom)" },
	{ name: "parskip", detail: "Vertical space between paragraphs instead of indents" },
	{ name: "indentfirst", detail: "Indent the first paragraph after a heading" },
	{ name: "multicol", detail: "Balanced multi-column text" },
	{ name: "changepage", detail: "Locally widen or shift the text block" },
	{ name: "afterpage", detail: "Run code after the current page ships out" },
	{ name: "lastpage", detail: "A label for the last page — 'page N of M'" },
	{ name: "pdfpages", detail: "Insert pages of an existing PDF" },
	{ name: "everypage", detail: "Hook code onto every page" },

	/* tables */
	{ name: "booktabs", detail: "Publication-quality horizontal rules" },
	{ name: "array", detail: "Extended column specifications" },
	{ name: "tabularx", detail: "Tables that fill a given width" },
	{ name: "tabulary", detail: "Tables with columns sized by content" },
	{ name: "longtable", detail: "Tables that break across pages" },
	{ name: "ltablex", detail: "tabularx and longtable combined" },
	{ name: "multirow", detail: "Cells spanning several rows" },
	{ name: "makecell", detail: "Line breaks and per-cell formatting" },
	{ name: "colortbl", detail: "Coloured rows, columns and cells" },
	{ name: "threeparttable", detail: "Tables with notes underneath" },
	{ name: "csvsimple", detail: "Typeset CSV files directly" },

	/* floats and captions */
	{ name: "float", detail: "The [H] placement and new float types" },
	{ name: "placeins", detail: "\\FloatBarrier to stop floats drifting" },
	{ name: "caption", detail: "Control caption format and spacing" },
	{ name: "subcaption", detail: "Sub-figures and sub-tables with their own captions" },
	{ name: "wrapfig", detail: "Wrap text around a figure" },
	{ name: "rotating", detail: "Rotated figures, tables and pages" },

	/* lists and text */
	{ name: "enumitem", detail: "Customise list labels and spacing" },
	{ name: "paralist", detail: "Compact and inline lists" },
	{ name: "microtype", detail: "Micro-typography — protrusion and font expansion" },
	{ name: "csquotes", detail: "Context-sensitive quotation marks" },
	{ name: "ragged2e", detail: "Ragged text with hyphenation" },
	{ name: "soul", detail: "Letterspacing, underlining and highlighting" },
	{ name: "ulem", detail: "Underlining and strike-out that break across lines" },
	{ name: "xspace", detail: "Smart space after a macro" },
	{ name: "textcomp", detail: "Extra text symbols" },
	{ name: "url", detail: "Typeset URLs with sensible line breaks" },
	{ name: "hyphenat", detail: "Control hyphenation" },

	/* fonts and encoding */
	{ name: "inputenc", detail: "Input encoding (unnecessary since 2018 — UTF-8 is default)" },
	{ name: "fontenc", detail: "Output font encoding; use [T1] for proper 8-bit fonts" },
	{ name: "babel", detail: "Multilingual typesetting and hyphenation" },
	{ name: "polyglossia", detail: "Multilingual support for XeTeX/LuaTeX" },
	{ name: "fontspec", detail: "System OpenType fonts (XeTeX/LuaTeX)" },
	{ name: "lmodern", detail: "Latin Modern fonts" },
	{ name: "newtxtext", detail: "Times-like text fonts" },
	{ name: "newtxmath", detail: "Times-like math fonts" },
	{ name: "mathpazo", detail: "Palatino text and math" },
	{ name: "helvet", detail: "Helvetica as the sans-serif family" },
	{ name: "courier", detail: "Courier as the monospace family" },
	{ name: "beramono", detail: "Bera Mono — a readable code font" },
	{ name: "inconsolata", detail: "Inconsolata monospace" },
	{ name: "fontawesome5", detail: "Font Awesome icons" },

	/* references and bibliography */
	{ name: "hyperref", detail: "Hyperlinks, PDF bookmarks and metadata" },
	{ name: "cleveref", detail: "References that name their own type" },
	{ name: "varioref", detail: "References that mention the page when it differs" },
	{ name: "natbib", detail: "Author-year and numeric citation styles" },
	{ name: "biblatex", detail: "Modern bibliography system, driven by biber" },
	{ name: "cite", detail: "Sorted and compressed numeric citations" },
	{ name: "bibentry", detail: "Inline a full bibliography entry" },
	{ name: "makeidx", detail: "Build an index" },
	{ name: "imakeidx", detail: "Index building without an external run" },
	{ name: "glossaries", detail: "Glossaries, acronyms and symbol lists" },
	{ name: "acronym", detail: "Acronyms expanded on first use" },
	{ name: "nomencl", detail: "Nomenclature list" },

	/* code and algorithms */
	{ name: "listings", detail: "Source code with keyword highlighting" },
	{ name: "minted", detail: "Source code highlighted by Pygments (needs shell-escape)" },
	{ name: "fancyvrb", detail: "Verbatim with options and framing" },
	{ name: "verbatimbox", detail: "Verbatim content inside boxes" },
	{ name: "algorithm", detail: "Floating environment for algorithms" },
	{ name: "algorithm2e", detail: "Algorithm typesetting, self-contained" },
	{ name: "algorithmic", detail: "Classic pseudocode environment" },
	{ name: "algpseudocode", detail: "Pseudocode layer of algorithmicx" },
	{ name: "algorithmicx", detail: "Framework behind algpseudocode" },

	/* science and data */
	{ name: "siunitx", detail: "Numbers, units and quantities, typeset consistently" },
	{ name: "chemfig", detail: "Chemical structure diagrams" },
	{ name: "mhchem", detail: "Chemical formulas and equations" },
	{ name: "circuitikz", detail: "Circuit diagrams built on TikZ" },
	{ name: "musixtex", detail: "Music notation" },

	/* structure and utilities */
	{ name: "appendix", detail: "Appendix formatting and per-chapter appendices" },
	{ name: "import", detail: "\\input from other directories, relative paths intact" },
	{ name: "subfiles", detail: "Compile chapters standalone or as one document" },
	{ name: "xparse", detail: "Rich argument specifications for new commands" },
	{ name: "etoolbox", detail: "Hooks and programming tools for class/package authors" },
	{ name: "ifthen", detail: "Conditionals in document code" },
	{ name: "xifthen", detail: "Extended conditionals" },
	{ name: "calc", detail: "Arithmetic in length and counter arguments" },
	{ name: "pgfkeys", detail: "Key-value option parsing" },
	{ name: "environ", detail: "Define environments that capture their whole body" },
	{ name: "comment", detail: "Comment out whole blocks" },
	{ name: "version", detail: "Include or exclude marked blocks" },
	{ name: "todonotes", detail: "To-do notes in the margin plus a summary list" },
	{ name: "draftwatermark", detail: "DRAFT watermark across the page" },
	{ name: "lipsum", detail: "Filler text for layout work" },
	{ name: "blindtext", detail: "Filler text, including whole sections" },
	{ name: "datetime2", detail: "Date and time formatting" },
	{ name: "lineno", detail: "Line numbers in the margin, for review" },
	{ name: "xr", detail: "Cross-reference labels in another document" },
	{ name: "attachfile", detail: "Attach files to the PDF" },
	{ name: "bookmark", detail: "Better PDF bookmark control" },
	{ name: "microtype-show", detail: "Debug view of microtype's adjustments" },
];

/* -------------------------------------------------------------- classes */

export const LATEX_CLASSES: readonly LatexClass[] = [
	{ name: "article", detail: "Short documents — papers, notes. No \\chapter." },
	{ name: "report", detail: "Longer documents with chapters, single-sided" },
	{ name: "book", detail: "Books — chapters, two-sided, front/main/back matter" },
	{ name: "letter", detail: "Correspondence" },
	{ name: "beamer", detail: "Presentation slides" },
	{ name: "memoir", detail: "Book class with layout customisation built in" },
	{ name: "scrartcl", detail: "KOMA-Script article — European typographic defaults" },
	{ name: "scrreprt", detail: "KOMA-Script report" },
	{ name: "scrbook", detail: "KOMA-Script book" },
	{ name: "scrlttr2", detail: "KOMA-Script letter" },
	{ name: "standalone", detail: "A single figure or table, cropped to its content" },
	{ name: "exam", detail: "Exams with questions, points and answer keys" },
	{ name: "moderncv", detail: "Curriculum vitae with several themes" },
	{ name: "IEEEtran", detail: "IEEE journals and conferences" },
	{ name: "acmart", detail: "ACM journals and proceedings" },
	{ name: "revtex4-2", detail: "APS and AIP journals (Physical Review)" },
	{ name: "elsarticle", detail: "Elsevier journals" },
	{ name: "llncs", detail: "Springer Lecture Notes in Computer Science" },
	{ name: "tufte-book", detail: "Tufte-style book with wide margin notes" },
	{ name: "tufte-handout", detail: "Tufte-style handout" },
];
