// Regenerate the TypeScript declarations from the Rust definitions.
//
// The types live in `crates/glyphtex-tex-api`, which is deliberately free of C
// dependencies and of the engine itself — so this runs on any machine, with no
// Emscripten toolchain required.
import { execFileSync } from 'node:child_process';
import { mkdirSync, readdirSync, writeFileSync } from 'node:fs';
import { dirname, join, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const here = dirname(fileURLToPath(import.meta.url));
const pkgRoot = resolve(here, '..');
const crateDir = resolve(pkgRoot, '../../crates/glyphtex-tex-api');
const outDir = join(pkgRoot, 'src/generated');

mkdirSync(outDir, { recursive: true });

// ts-rs exports during `cargo test`; TS_RS_EXPORT_DIR redirects where.
execFileSync('cargo', ['test', '--quiet'], {
	cwd: crateDir,
	env: { ...process.env, TS_RS_EXPORT_DIR: outDir },
	stdio: 'inherit'
});

// ts-rs emits one file per type but no entry point; write a barrel so consumers
// can `import type { CompileResult } from 'glyphtex-engine'`.
const modules = readdirSync(outDir)
	.filter((f) => f.endsWith('.ts') && f !== 'index.ts')
	.map((f) => f.replace(/\.ts$/, ''))
	.sort();

const barrel = [
	'// Generated by scripts/generate-types.mjs. Do not edit.',
	...modules.map((m) => `export type { ${m} } from './${m}.js';`),
	''
].join('\n');

writeFileSync(join(outDir, 'index.ts'), barrel);
console.log(`generated ${modules.length} types into src/generated/`);
