// Generates icon components from an Iconify set (@iconify-json/tabler) into
// src/components/ui/icons/generated/, plus a barrel. Run: node scripts/gen-icons.mjs
import { createRequire } from 'node:module';
import { mkdirSync, rmSync, writeFileSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';
import { ICON_MAP } from './icon-map.mjs';

const require = createRequire(import.meta.url);
const here = dirname(fileURLToPath(import.meta.url));
const outDir = resolve(here, '../src/components/ui/icons/generated');
const data = require('@iconify-json/tabler/icons.json');
const W = data.width ?? 256;
const H = data.height ?? 256;

rmSync(outDir, { recursive: true, force: true });
mkdirSync(outDir, { recursive: true });

const component = (body) => `<script lang="ts">
  import type { SVGAttributes } from "svelte/elements";
  let {
    size = 18,
    class: className = undefined,
    ...rest
  }: { size?: number | string; class?: string } & SVGAttributes<SVGSVGElement> = $props();
</script>

<svg
  xmlns="http://www.w3.org/2000/svg"
  width={size}
  height={size}
  viewBox="0 0 ${W} ${H}"
  class={className}
  aria-hidden="true"
  {...rest}
>${body}</svg>
`;

const exports = [];
for (const [name, slug] of Object.entries(ICON_MAP)) {
	const icon = data.icons[slug];
	if (!icon) throw new Error(`missing ${data.prefix}:${slug} for ${name}`);
	writeFileSync(resolve(outDir, `${name}.svelte`), component(icon.body));
	exports.push(`export { default as ${name} } from "./generated/${name}.svelte";`);
}

writeFileSync(
	resolve(here, '../src/components/ui/icons/index.ts'),
	`// Generated by scripts/gen-icons.mjs. Do not edit by hand.\n${exports.sort().join('\n')}\n`
);

console.log(`Generated ${exports.length} ${data.prefix} icons -> ${outDir}`);
