import type { PackageData } from "./index";

// Incompatible with `algorithm`, `algorithmic` and `algpseudocode`.
export const data: PackageData = {
	commands: [
		/* --- headers --- */
		{
			name: "KwIn",
			snippet: "KwIn{$1}$0",
			detail: "The algorithm's Input line",
			example: "\\KwIn{An array $A$ of $n$ integers}",
			package: "algorithm2e",
		},
		{
			name: "KwOut",
			snippet: "KwOut{$1}$0",
			detail: "The algorithm's Output line",
			package: "algorithm2e",
		},
		{
			name: "KwData",
			snippet: "KwData{$1}$0",
			detail: "The algorithm's Data line",
			package: "algorithm2e",
		},
		{
			name: "KwResult",
			snippet: "KwResult{$1}$0",
			detail: "The algorithm's Result line",
			package: "algorithm2e",
		},
		{
			name: "SetKwInOut",
			snippet: "SetKwInOut{${1:Input}}{${2:input}}$0",
			detail: "Define your own input/output header keyword",
			doc: "Preamble. `\\SetKwInOut{Parameters}{parameters}` gives you `\\Parameters{…}` aligned with the built-in headers.",
			example: "\\SetKwInOut{Params}{Parameters}",
			package: "algorithm2e",
		},
		{
			name: "SetKwInput",
			snippet: "SetKwInput{${1:Name}}{${2:text}}$0",
			detail: "Define a header keyword without the alignment",
			package: "algorithm2e",
		},

		/* --- control flow --- */
		{
			name: "If",
			snippet: "If{$1}{\n\t$0\n}",
			detail: "Conditional block",
			doc: "Chain with `\\uIf` (no end mark) followed by `\\ElseIf`/`\\Else`. The bare `\\If` prints an end-of-block marker, which is why the chained forms use the `u` prefix.",
			example: "\\uIf{$x > 0$}{positive\\;}\n\\Else{non-positive\\;}",
			package: "algorithm2e",
		},
		{
			name: "uIf",
			snippet: "uIf{$1}{\n\t$0\n}",
			detail: "Conditional with no end-of-block marker (for chaining)",
			package: "algorithm2e",
		},
		{
			name: "ElseIf",
			snippet: "ElseIf{$1}{\n\t$0\n}",
			detail: "Further condition in an if-chain",
			package: "algorithm2e",
		},
		{
			name: "uElseIf",
			snippet: "uElseIf{$1}{\n\t$0\n}",
			detail: "Further condition, no end-of-block marker",
			package: "algorithm2e",
		},
		{
			name: "Else",
			snippet: "Else{\n\t$0\n}",
			detail: "Final branch of an if-chain",
			package: "algorithm2e",
		},
		{
			name: "uElse",
			snippet: "uElse{\n\t$0\n}",
			detail: "Final branch, no end-of-block marker",
			package: "algorithm2e",
		},
		{
			name: "eIf",
			snippet: "eIf{$1}{\n\t$2\n}{\n\t$0\n}",
			detail: "If/else as a single command with two bodies",
			doc: "Often the tidiest form: condition, then-body and else-body in one place.",
			example: "\\eIf{$n = 0$}{return 1\\;}{return $n \\cdot f(n-1)$\\;}",
			package: "algorithm2e",
		},
		{
			name: "While",
			snippet: "While{$1}{\n\t$0\n}",
			detail: "While loop",
			example: "\\While{$i < n$}{$i \\gets i + 1$\\;}",
			package: "algorithm2e",
		},
		{
			name: "For",
			snippet: "For{$1}{\n\t$0\n}",
			detail: "For loop",
			example: "\\For{$i \\gets 1$ \\KwTo $n$}{visit $A[i]$\\;}",
			package: "algorithm2e",
		},
		{
			name: "ForEach",
			snippet: "ForEach{$1}{\n\t$0\n}",
			detail: "For-each loop",
			example: "\\ForEach{$v \\in V$}{mark $v$\\;}",
			package: "algorithm2e",
		},
		{
			name: "ForAll",
			snippet: "ForAll{$1}{\n\t$0\n}",
			detail: "For-all loop",
			package: "algorithm2e",
		},
		{
			name: "Repeat",
			snippet: "Repeat{$1}{\n\t$0\n}",
			detail: "Repeat-until loop — the condition comes first, the body second",
			doc: "Reads backwards from how it prints: `\\Repeat{until-condition}{body}`.",
			package: "algorithm2e",
		},
		{
			name: "Switch",
			snippet: "Switch{$1}{\n\t\\Case{$2}{$0}\n}",
			detail: "Switch block, containing \\Case and \\Other",
			package: "algorithm2e",
		},
		{
			name: "Case",
			snippet: "Case{$1}{\n\t$0\n}",
			detail: "One case of a switch",
			package: "algorithm2e",
		},
		{
			name: "Other",
			snippet: "Other{\n\t$0\n}",
			detail: "Default case of a switch",
			package: "algorithm2e",
		},
		{ name: "KwTo", detail: "The word 'to' in a for-loop range", package: "algorithm2e" },
		{ name: "KwRet", snippet: "KwRet{$1}$0", detail: "A return statement", package: "algorithm2e" },
		{ name: "Return", snippet: "Return{$1}$0", detail: "A return statement", example: "\\Return $x$\\;", package: "algorithm2e" },
		{ name: "KwSty", snippet: "KwSty{$1}$0", detail: "Typeset text in the keyword style", package: "algorithm2e" },

		/* --- comments and layout --- */
		{
			name: "tcc",
			snippet: "tcc{$1}$0",
			detail: "A comment on its own line",
			doc: "`\\tcc*{…}` puts the comment at the end of the current line instead.",
			example: "\\tcc{invariant: $A[1..i]$ is sorted}",
			package: "algorithm2e",
		},
		{
			name: "tcp",
			snippet: "tcp{$1}$0",
			detail: "A comment in the alternative comment style",
			doc: "`\\tcp*{…}` is the end-of-line form; `\\tcp*[r]{…}` right-aligns it.",
			example: "$i \\gets i + 1$ \\tcp*{advance}",
			package: "algorithm2e",
		},
		{
			name: "SetKwComment",
			snippet: "SetKwComment{${1:Comment}}{${2:/* }}{${3: */}}$0",
			detail: "Define a comment style with its own delimiters",
			package: "algorithm2e",
		},
		{
			name: "SetAlgoLined",
			detail: "Draw vertical lines linking each block to its end",
			doc: "The alternatives are `\\SetAlgoNoLine` and `\\SetAlgoVlined`. Set it once in the preamble.",
			package: "algorithm2e",
		},
		{ name: "SetAlgoNoLine", detail: "No block lines, indentation only", package: "algorithm2e" },
		{ name: "SetAlgoVlined", detail: "Vertical block lines without the end marks", package: "algorithm2e" },
		{
			name: "SetNoFillComment",
			detail: "Stop comments being padded to the full line width",
			package: "algorithm2e",
		},
		{
			name: "DontPrintSemicolon",
			detail: "Hide the end-of-line semicolons",
			doc: "You still write `\\;` at the end of each statement; this only stops it printing.",
			example: "\\DontPrintSemicolon",
			package: "algorithm2e",
		},
		{ name: "PrintSemicolon", detail: "Show the end-of-line semicolons again", package: "algorithm2e" },
		{
			name: "SetKwFunction",
			snippet: "SetKwFunction{${1:FMain}}{${2:Main}}$0",
			detail: "Declare a function name usable as a macro",
			doc: "Preamble. `\\SetKwFunction{FSort}{Sort}` lets you write `\\FSort{$A$}` and have the name typeset consistently everywhere.",
			example: "\\SetKwFunction{FSort}{MergeSort}",
			package: "algorithm2e",
		},
		{
			name: "SetKwProg",
			snippet: "SetKwProg{${1:Fn}}{${2:Function}}{${3::}}{}$0",
			detail: "Declare a procedure/function block keyword",
			doc: "Combined with `\\SetKwFunction` this is how you typeset a named subroutine with its own body: `\\Fn{\\FSort{$A$}}{…}`.",
			package: "algorithm2e",
		},
		{
			name: "SetKw",
			snippet: "SetKw{${1:KwBreak}}{${2:break}}$0",
			detail: "Declare a simple keyword",
			package: "algorithm2e",
		},
		{
			name: "SetKwData",
			snippet: "SetKwData{${1:Name}}{${2:text}}$0",
			detail: "Declare a data-name macro, typeset in the data style",
			package: "algorithm2e",
		},
		{
			name: "SetAlgoCaptionSeparator",
			snippet: "SetAlgoCaptionSeparator{${1::}}$0",
			detail: "Change the separator between caption number and text",
			package: "algorithm2e",
		},
		{
			name: "listofalgorithms",
			detail: "Insert the list of algorithms",
			package: "algorithm2e",
			context: "text",
		},
		{
			name: "IncMargin",
			snippet: "IncMargin{${1:1em}}$0",
			detail: "Widen the left margin of the following algorithms",
			package: "algorithm2e",
		},
		{
			name: "DecMargin",
			snippet: "DecMargin{${1:1em}}$0",
			detail: "Narrow the left margin again",
			package: "algorithm2e",
		},
		{
			name: "nl",
			detail: "Force a line number on this line",
			doc: "`\\nonl` does the opposite and suppresses one.",
			package: "algorithm2e",
		},
		{ name: "nonl", detail: "Suppress the line number on this line", package: "algorithm2e" },
		{
			name: "lIf",
			snippet: "lIf{$1}{$2}$0",
			detail: "Single-line if — condition and body on one line",
			doc: "The `l` prefix means 'one line' and exists for `\\lIf`, `\\lElse`, `\\lFor` and `\\lWhile`.",
			example: "\\lIf{$x < 0$}{$x \\gets -x$}",
			package: "algorithm2e",
		},
		{ name: "lElse", snippet: "lElse{$1}$0", detail: "Single-line else", package: "algorithm2e" },
		{ name: "lFor", snippet: "lFor{$1}{$2}$0", detail: "Single-line for loop", package: "algorithm2e" },
		{ name: "lWhile", snippet: "lWhile{$1}{$2}$0", detail: "Single-line while loop", package: "algorithm2e" },
	],
	environments: [
		{
			name: "algorithm",
			detail: "Floating algorithm (algorithm2e)",
			body: "[${1:H}]\n\t\\caption{$2}\n\t\\KwIn{$3}\n\t\\KwOut{$4}\n\t$0\n",
			package: "algorithm2e",
			context: "text",
		},
		{
			name: "algorithm*",
			detail: "Full-width floating algorithm (two-column)",
			body: "[${1:H}]\n\t\\caption{$2}\n\t$0\n",
			package: "algorithm2e",
			context: "text",
		},
		{
			name: "algorithmic",
			detail: "Non-floating algorithm body",
			body: "\n\t$0\n",
			package: "algorithm2e",
			context: "text",
		},
		{
			name: "procedure",
			detail: "Floating procedure, numbered separately from algorithms",
			body: "[${1:H}]\n\t\\caption{$2}\n\t$0\n",
			package: "algorithm2e",
			context: "text",
		},
		{
			name: "function",
			detail: "Floating function, numbered separately from algorithms",
			body: "[${1:H}]\n\t\\caption{$2}\n\t$0\n",
			package: "algorithm2e",
			context: "text",
		},
	],
};
