import type { PackageData } from "./index";

export const data: PackageData = {
	commands: [
		/* --- frames and titles --- */
		{
			name: "frametitle",
			snippet: "frametitle{$1}$0",
			detail: "Title of the current slide",
			doc: "Goes just inside `\\begin{frame}`. The optional argument gives a shorter form for the navigation bars.",
			example: "\\frametitle{Results}",
			package: "beamer",
			context: "text",
		},
		{
			name: "framesubtitle",
			snippet: "framesubtitle{$1}$0",
			detail: "Subtitle under the frame title",
			package: "beamer",
			context: "text",
		},
		{
			name: "titlepage",
			detail: "Typeset the title slide",
			doc: "Usually the whole content of the first frame: `\\begin{frame}\\titlepage\\end{frame}`, or `\\frame{\\titlepage}`.",
			example: "\\begin{frame}\n\t\\titlepage\n\\end{frame}",
			package: "beamer",
			context: "text",
		},
		{
			name: "subtitle",
			snippet: "subtitle{$1}$0",
			detail: "Presentation subtitle for the title slide",
			package: "beamer",
			context: "text",
		},
		{
			name: "institute",
			snippet: "institute{$1}$0",
			detail: "Author's institution on the title slide",
			doc: "The optional argument is a short form used in the footline.",
			example: "\\institute[MIT]{Massachusetts Institute of Technology}",
			package: "beamer",
			context: "text",
		},
		{
			name: "logo",
			snippet: "logo{\\includegraphics[height=${1:1cm}]{${2:logo}}}$0",
			detail: "Logo placed by the theme on every slide",
			package: "beamer",
			context: "text",
		},
		{
			name: "frame",
			snippet: "frame{$1}$0",
			detail: "A slide, in command form",
			doc: "Short form of the `frame` environment. The environment is preferred — verbatim content needs `[fragile]`, which only the environment accepts.",
			package: "beamer",
			context: "text",
		},
		{
			name: "framezoom",
			snippet: "framezoom<${1:1}><${2:2}>[]($3,$4)($5,$6)$0",
			detail: "Magnify a region of the slide on a later overlay",
			package: "beamer",
			context: "text",
		},
		{
			name: "againframe",
			snippet: "againframe<${1:2}>{${2:label}}$0",
			detail: "Show a labelled frame again, at other overlays",
			doc: "Needs the original frame to carry `\\begin{frame}[label=name]`. The way to revisit an outline slide between sections.",
			example: "\\againframe<2>{outline}",
			package: "beamer",
			context: "text",
		},
		{
			name: "appendix",
			detail: "Start backup slides, excluded from the frame count",
			doc: "Everything after it still compiles but no longer counts towards the total shown in the footline.",
			package: "beamer",
			context: "text",
		},

		/* --- overlays --- */
		{
			name: "pause",
			detail: "Split the slide into overlays at this point",
			doc: "Everything after it moves to the next overlay. Simple, but it does not compose — reach for `\\onslide` or `\\uncover` as soon as the timing gets interesting.",
			package: "beamer",
			context: "text",
		},
		{
			name: "onslide",
			snippet: "onslide<${1:2-}>{$2}$0",
			detail: "Show content only on the given overlays, keeping its space",
			doc: "Without the braced argument it acts as a switch until the next `\\onslide`. Hidden content still occupies room, so nothing jumps.",
			example: "\\onslide<2->{This appears second.}",
			package: "beamer",
			context: "text",
		},
		{
			name: "only",
			snippet: "only<${1:2}>{$2}$0",
			detail: "Include content only on the given overlays, reserving no space",
			doc: "The counterpart to `\\uncover`: the material genuinely is not there on other overlays, so the layout reflows.",
			example: "\\only<2>{Just for slide two.}",
			package: "beamer",
			context: "text",
		},
		{
			name: "uncover",
			snippet: "uncover<${1:2-}>{$2}$0",
			detail: "Reveal content on the given overlays, keeping its space",
			doc: "Hidden material is typeset transparently or invisibly, so the slide never shifts as items appear.",
			example: "\\uncover<3->{The conclusion.}",
			package: "beamer",
			context: "text",
		},
		{
			name: "visible",
			snippet: "visible<${1:2-}>{$2}$0",
			detail: "Like \\uncover, but never shows a transparent preview",
			package: "beamer",
			context: "text",
		},
		{
			name: "invisible",
			snippet: "invisible<${1:2}>{$2}$0",
			detail: "Hide content on the given overlays",
			package: "beamer",
			context: "text",
		},
		{
			name: "alt",
			snippet: "alt<${1:2}>{${2:then}}{${3:otherwise}}$0",
			detail: "One of two versions, depending on the overlay",
			example: "\\alt<2>{after}{before}",
			package: "beamer",
			context: "text",
		},
		{
			name: "temporal",
			snippet: "temporal<${1:2}>{${2:before}}{${3:during}}{${4:after}}$0",
			detail: "Three versions: before, during and after the given overlays",
			package: "beamer",
			context: "text",
		},
		{
			name: "alert",
			snippet: "alert{$1}$0",
			detail: "Highlight text in the theme's alert colour",
			doc: "Takes an overlay specification, which is how you highlight one word on one overlay: `\\alert<2>{this}`.",
			example: "\\alert<2>{the important bit}",
			package: "beamer",
			context: "text",
		},
		{
			name: "structure",
			snippet: "structure{$1}$0",
			detail: "Typeset text in the theme's structure colour",
			package: "beamer",
			context: "text",
		},
		{
			name: "transdissolve",
			detail: "Dissolve transition into the next slide",
			doc: "Only some PDF viewers honour transitions in presentation mode.",
			package: "beamer",
			context: "text",
		},
		{
			name: "transblindsvertical",
			detail: "Vertical blinds transition into the next slide",
			package: "beamer",
			context: "text",
		},

		/* --- themes and appearance --- */
		{
			name: "usetheme",
			snippet: "usetheme{${1:Madrid}}$0",
			detail: "Load a beamer presentation theme",
			doc: "Common choices: `default`, `Madrid`, `Berlin`, `Copenhagen`, `Frankfurt`, `Warsaw`, `metropolis` (a separate install), `CambridgeUS`.",
			example: "\\usetheme{metropolis}",
			package: "beamer",
		},
		{
			name: "usecolortheme",
			snippet: "usecolortheme{${1:beaver}}$0",
			detail: "Load a colour theme on top of the presentation theme",
			doc: "`beaver`, `crane`, `dolphin`, `seahorse`, `whale`, `rose`, `orchid` — they combine, so a colour theme and an inner theme can be mixed freely.",
			package: "beamer",
		},
		{
			name: "usefonttheme",
			snippet: "usefonttheme{${1:professionalfonts}}$0",
			detail: "Load a font theme",
			doc: "`professionalfonts` is the one to remember: it stops beamer substituting its own maths fonts.",
			package: "beamer",
		},
		{
			name: "useinnertheme",
			snippet: "useinnertheme{${1:circles}}$0",
			detail: "Set the appearance of blocks, lists and the title page",
			package: "beamer",
		},
		{
			name: "useoutertheme",
			snippet: "useoutertheme{${1:infolines}}$0",
			detail: "Set the appearance of headline, footline and sidebars",
			package: "beamer",
		},
		{
			name: "setbeamertemplate",
			snippet: "setbeamertemplate{${1:navigation symbols}}{}$0",
			detail: "Redefine a beamer template element",
			doc: "The usual first line of any real presentation is `\\setbeamertemplate{navigation symbols}{}`, which removes the navigation icons. Also `caption`, `footline`, `itemize items`, `blocks`.",
			example: "\\setbeamertemplate{navigation symbols}{}",
			package: "beamer",
		},
		{
			name: "setbeamercolor",
			snippet: "setbeamercolor{${1:frametitle}}{fg=${2:white}, bg=${3:structure}}$0",
			detail: "Set the foreground/background of a beamer element",
			example: "\\setbeamercolor{block title}{bg=structure, fg=white}",
			package: "beamer",
		},
		{
			name: "setbeamerfont",
			snippet: "setbeamerfont{${1:frametitle}}{size=\\large, series=\\bfseries}$0",
			detail: "Set the font of a beamer element",
			package: "beamer",
		},
		{
			name: "setbeamersize",
			snippet: "setbeamersize{text margin left=${1:1em}, text margin right=${2:1em}}$0",
			detail: "Set frame margins and sidebar widths",
			package: "beamer",
		},
		{
			name: "beamertemplatenavigationsymbolsempty",
			detail: "Remove the navigation symbols (older spelling)",
			doc: "`\\setbeamertemplate{navigation symbols}{}` is the current way to say this.",
			package: "beamer",
		},

		/* --- structure and navigation --- */
		{
			name: "tableofcontents",
			snippet: "tableofcontents[currentsection]$0",
			detail: "Outline slide",
			doc: "Beamer's version takes options: `currentsection` greys out the others, `hideallsubsections` shortens it, `pausesections` reveals one at a time.",
			example: "\\tableofcontents[currentsection, hideothersubsections]",
			package: "beamer",
			context: "text",
		},
		{
			name: "AtBeginSection",
			snippet: "AtBeginSection[]{\n\t\\begin{frame}\n\t\t\\tableofcontents[currentsection]\n\t\\end{frame}\n}$0",
			detail: "Insert a frame automatically at each section start",
			doc: "The standard way to get recurring outline slides without pasting one before every section.",
			package: "beamer",
		},
		{
			name: "AtBeginSubsection",
			snippet: "AtBeginSubsection[]{\n\t$0\n}",
			detail: "Insert a frame automatically at each subsection start",
			package: "beamer",
		},
		{
			name: "hyperlink",
			snippet: "hyperlink{${1:target}}{\\beamerbutton{${2:label}}}$0",
			detail: "Link to a labelled frame",
			doc: "Pairs with `\\hypertarget` or a frame `label=`; add an overlay specification to jump to a particular overlay.",
			example: "\\hyperlink{backup}{\\beamerbutton{Details}}",
			package: "beamer",
			context: "text",
		},
		{
			name: "hypertarget",
			snippet: "hypertarget{${1:target}}{$2}$0",
			detail: "Mark a jump destination",
			package: "beamer",
			context: "text",
		},
		{
			name: "beamerbutton",
			snippet: "beamerbutton{$1}$0",
			detail: "A button-shaped link label",
			package: "beamer",
			context: "text",
		},
		{
			name: "beamergotobutton",
			snippet: "beamergotobutton{$1}$0",
			detail: "Button label with a 'go to' arrow",
			package: "beamer",
			context: "text",
		},
		{
			name: "insertframenumber",
			detail: "The current frame number",
			doc: "Usually paired with `\\inserttotalframenumber` in a footline template.",
			example: "\\insertframenumber/\\inserttotalframenumber",
			package: "beamer",
			context: "text",
		},
		{
			name: "inserttotalframenumber",
			detail: "Total number of frames",
			doc: "Needs two compilation runs to settle, and ignores anything after `\\appendix`.",
			package: "beamer",
			context: "text",
		},
		{ name: "insertsectionhead", detail: "Title of the current section", package: "beamer", context: "text" },
		{ name: "inserttitle", detail: "The presentation title", package: "beamer", context: "text" },
		{ name: "insertauthor", detail: "The presentation author", package: "beamer", context: "text" },
		{
			name: "note",
			snippet: "note{$1}$0",
			detail: "Speaker note attached to this frame",
			doc: "Shown only when the document class option `notes` (or `show notes on second screen`) is set.",
			example: "\\note<2>{Remember to mention the caveat.}",
			package: "beamer",
			context: "text",
		},
	],
	environments: [
		{
			name: "frame",
			detail: "A beamer slide",
			body: "{${1:Title}}\n\t$0\n",
			package: "beamer",
			context: "text",
		},
		{
			name: "columns",
			detail: "Side-by-side columns on a slide",
			body: "[T]\n\t$0\n",
			package: "beamer",
			context: "text",
		},
		{
			name: "column",
			detail: "One column of a beamer slide",
			body: "{${1:0.5\\textwidth}}\n\t$0\n",
			package: "beamer",
			context: "text",
		},
		{
			name: "block",
			detail: "Titled box on a slide",
			body: "{${1:Title}}\n\t$0\n",
			package: "beamer",
			context: "text",
		},
		{
			name: "alertblock",
			detail: "Emphasised box on a slide",
			body: "{${1:Title}}\n\t$0\n",
			package: "beamer",
			context: "text",
		},
		{
			name: "exampleblock",
			detail: "Example box on a slide",
			body: "{${1:Title}}\n\t$0\n",
			package: "beamer",
			context: "text",
		},
		{
			name: "theorem",
			detail: "Theorem block, styled by the theme",
			body: "\n\t$0\n",
			package: "beamer",
			context: "text",
		},
		{
			name: "overlayarea",
			detail: "Fixed-size area whose content changes per overlay",
			body: "{${1:\\textwidth}}{${2:4cm}}\n\t$0\n",
			package: "beamer",
			context: "text",
		},
		{
			name: "onlyenv",
			detail: "Environment form of \\only",
			body: "<${1:2}>\n\t$0\n",
			package: "beamer",
			context: "text",
		},
		{
			name: "uncoverenv",
			detail: "Environment form of \\uncover",
			body: "<${1:2-}>\n\t$0\n",
			package: "beamer",
			context: "text",
		},
	],
};
