/**
 * `biblatex` — the modern bibliography and citation system.
 *
 * Replaces the classic `\bibliography`/BibTeX workflow entirely: sources are
 * declared in the preamble with `\addbibresource`, the list is printed with
 * `\printbibliography`, and styles are chosen through package options rather
 * than a `.bst` file. It wants the Biber backend —
 * `\usepackage[backend=biber,style=authoryear]{biblatex}` — which means the
 * build runs latex → biber → latex → latex, not bibtex.
 */
import type { PackageData } from "./index";

export const data: PackageData = {
	commands: [
		/* --- resources and printing ------------------------------------------ */
		{
			name: "addbibresource",
			snippet: "addbibresource{${1:refs.bib}}$0",
			detail: "Register a .bib file",
			doc: "Preamble only, and the extension is required — unlike BibTeX's `\\bibliography{refs}`, biblatex wants `refs.bib`.",
			example: "\\addbibresource{references.bib}",
			package: "biblatex",
		},
		{
			name: "printbibliography",
			snippet: "printbibliography$0",
			detail: "Typeset the bibliography",
			doc: "Options filter and retitle it: `[title=References]`, `[keyword=primary]`, `[type=article]`, `[heading=bibintoc]` to add a ToC entry.",
			example: "\\printbibliography[title={References},heading=bibintoc]",
			package: "biblatex",
			context: "text",
		},
		{
			name: "printbibheading",
			snippet: "printbibheading[title={${1:References}}]$0",
			detail: "Print only a bibliography heading",
			doc: "Useful when splitting one bibliography into several `\\printbibliography[heading=subbibliography]` sections under a shared title.",
			package: "biblatex",
			context: "text",
		},
		{
			name: "printshorthands",
			snippet: "printshorthands$0",
			detail: "Print the list of shorthands",
			package: "biblatex",
			context: "text",
		},
		{
			name: "bibliography",
			snippet: "bibliography{${1:refs}}$0",
			detail: "Legacy .bib declaration (prefer \\addbibresource)",
			doc: "Accepted for compatibility, but `\\addbibresource` is the biblatex way and the only one that takes options.",
			package: "biblatex",
		},

		/* --- everyday citation ------------------------------------------------ */
		{
			name: "cite",
			snippet: "cite{$1}$0",
			detail: "Plain citation in the current style",
			doc: "The optional arguments are prenote and postnote: `\\cite[see][p.~5]{key}`.",
			example: "\\cite[p.~42]{knuth1984}",
			package: "biblatex",
			context: "text",
		},
		{
			name: "autocite",
			snippet: "autocite{$1}$0",
			detail: "Citation that follows the package's autocite setting",
			doc: "Dispatches to `\\parencite`, `\\footcite` or another form depending on `autocite=` — the right default when a document may change style later.",
			example: "\\autocite[cf.][15]{fowler2018}",
			package: "biblatex",
			context: "text",
		},
		{
			name: "parencite",
			snippet: "parencite{$1}$0",
			detail: "Citation in parentheses",
			example: "The result is well known \\parencite{knuth1984}.",
			package: "biblatex",
			context: "text",
		},
		{
			name: "textcite",
			snippet: "textcite{$1}$0",
			detail: "Citation as part of the sentence",
			doc: "Author in running text, year in parentheses: “Knuth (1984) showed …”. The in-text counterpart of `\\parencite`.",
			example: "\\textcite{knuth1984} introduced literate programming.",
			package: "biblatex",
			context: "text",
		},
		{
			name: "footcite",
			snippet: "footcite{$1}$0",
			detail: "Citation in a footnote",
			package: "biblatex",
			context: "text",
		},
		{
			name: "footcitetext",
			snippet: "footcitetext{$1}$0",
			detail: "Footnote citation without the footnote mark",
			package: "biblatex",
			context: "text",
		},
		{
			name: "smartcite",
			snippet: "smartcite{$1}$0",
			detail: "Footnote citation in text, parenthetical in a footnote",
			package: "biblatex",
			context: "text",
		},
		{
			name: "supercite",
			snippet: "supercite{$1}$0",
			detail: "Superscripted numeric citation",
			package: "biblatex",
			context: "text",
		},
		{
			name: "citep",
			snippet: "citep{$1}$0",
			detail: "natbib-compatible parenthetical citation",
			doc: "Only defined with the `natbib=true` package option; `\\parencite` is the native spelling.",
			package: "biblatex",
			context: "text",
		},
		{
			name: "citet",
			snippet: "citet{$1}$0",
			detail: "natbib-compatible textual citation",
			doc: "Only defined with the `natbib=true` package option; `\\textcite` is the native spelling.",
			package: "biblatex",
			context: "text",
		},

		/* --- citation parts --------------------------------------------------- */
		{
			name: "citeauthor",
			snippet: "citeauthor{$1}$0",
			detail: "Author name only",
			example: "As \\citeauthor{knuth1984} argues, \\dots",
			package: "biblatex",
			context: "text",
		},
		{
			name: "citetitle",
			snippet: "citetitle{$1}$0",
			detail: "Title only",
			doc: "`\\citetitle*{…}` prints the full title rather than the abbreviated one.",
			package: "biblatex",
			context: "text",
		},
		{
			name: "citeyear",
			snippet: "citeyear{$1}$0",
			detail: "Year only",
			package: "biblatex",
			context: "text",
		},
		{
			name: "citedate",
			snippet: "citedate{$1}$0",
			detail: "Full date of the entry",
			package: "biblatex",
			context: "text",
		},
		{
			name: "citeurl",
			snippet: "citeurl{$1}$0",
			detail: "URL field of the entry",
			package: "biblatex",
			context: "text",
		},
		{
			name: "fullcite",
			snippet: "fullcite{$1}$0",
			detail: "Full bibliography entry inline",
			doc: "Typesets the entry as it would appear in the bibliography — handy in footnotes and in “further reading” lists.",
			package: "biblatex",
			context: "text",
		},
		{
			name: "footfullcite",
			snippet: "footfullcite{$1}$0",
			detail: "Full bibliography entry in a footnote",
			package: "biblatex",
			context: "text",
		},
		{
			name: "nocite",
			snippet: "nocite{$1}$0",
			detail: "Add to the bibliography without citing",
			doc: "`\\nocite{*}` pulls in every entry of every registered resource — the usual way to print a complete reading list.",
			example: "\\nocite{*}",
			package: "biblatex",
			context: "text",
		},
		{
			name: "citeauthor*",
			snippet: "citeauthor*{$1}$0",
			detail: "Author name, never abbreviated to “ibid.”",
			package: "biblatex",
			context: "text",
		},
		{
			name: "cites",
			snippet: "cites{$1}{$2}$0",
			detail: "Multi-citation with per-entry pre/postnotes",
			doc: "Each key gets its own brace group, so notes stay attached: `\\cites[10]{a}[see][20]{b}`. Every cite command has a plural `…s` form.",
			example: "\\cites[5]{knuth1984}[see][12]{lamport1994}",
			package: "biblatex",
			context: "text",
		},
		{
			name: "parencites",
			snippet: "parencites{$1}{$2}$0",
			detail: "Several sources in one set of parentheses",
			package: "biblatex",
			context: "text",
		},
		{
			name: "textcites",
			snippet: "textcites{$1}{$2}$0",
			detail: "Several sources woven into the sentence",
			package: "biblatex",
			context: "text",
		},

		/* --- configuration ---------------------------------------------------- */
		{
			name: "defbibheading",
			snippet: "defbibheading{${1:name}}[${2:Title}]{$0}",
			detail: "Define a bibliography heading",
			doc: "The body receives the printed title as `#1`. Select it later with `\\printbibliography[heading=name]`.",
			example: "\\defbibheading{primary}[Primary sources]{\\section*{#1}}",
			package: "biblatex",
		},
		{
			name: "defbibnote",
			snippet: "defbibnote{${1:name}}{$0}",
			detail: "Define a note to print with a bibliography",
			doc: "Attach it with `\\printbibliography[prenote=name]` or `[postnote=name]`.",
			package: "biblatex",
		},
		{
			name: "defbibfilter",
			snippet: "defbibfilter{${1:name}}{$0}",
			detail: "Define a reusable bibliography filter",
			example: "\\defbibfilter{online}{\\type{online} or \\type{misc}}",
			package: "biblatex",
		},
		{
			name: "defbibcheck",
			snippet: "defbibcheck{${1:name}}{$0}",
			detail: "Define a per-entry bibliography check",
			package: "biblatex",
		},
		{
			name: "DeclareLanguageMapping",
			snippet: "DeclareLanguageMapping{${1:english}}{${2:english-apa}}$0",
			detail: "Map a babel language to a biblatex .lbx file",
			doc: "Required by several styles (notably `apa`) so localisation strings match the chosen style.",
			example: "\\DeclareLanguageMapping{english}{english-apa}",
			package: "biblatex",
		},
		{
			name: "DeclareFieldFormat",
			snippet: "DeclareFieldFormat{${1:title}}{$0}",
			detail: "Change how one bibliography field is formatted",
			example: "\\DeclareFieldFormat{title}{\\mkbibquote{#1}}",
			package: "biblatex",
		},
		{
			name: "DeclareNameAlias",
			snippet: "DeclareNameAlias{${1:sortname}}{${2:last-first}}$0",
			detail: "Alias a name format to another",
			package: "biblatex",
		},
		{
			name: "AtEveryBibitem",
			snippet: "AtEveryBibitem{$0}",
			detail: "Hook run before every bibliography entry",
			doc: "The usual place to drop unwanted fields: `\\AtEveryBibitem{\\clearfield{note}}`.",
			package: "biblatex",
		},
		{
			name: "ExecuteBibliographyOptions",
			snippet: "ExecuteBibliographyOptions{$0}",
			detail: "Set biblatex options after loading",
			example: "\\ExecuteBibliographyOptions{maxbibnames=99,giveninits=true}",
			package: "biblatex",
		},
		{
			name: "addbibresource*",
			snippet: "addbibresource*{${1:refs.bib}}$0",
			detail: "Register a .bib file, ignoring a missing file",
			package: "biblatex",
		},
	],
	environments: [
		{
			name: "refsection",
			detail: "A self-contained bibliography section",
			body: "\n\t$0\n",
			package: "biblatex",
			context: "text",
		},
		{
			name: "refsegment",
			detail: "A numbered segment within a refsection",
			body: "\n\t$0\n",
			package: "biblatex",
			context: "text",
		},
	],
};
