import type { PackageData } from "./index";

export const data: PackageData = {
	commands: [
		{
			name: "includegraphics",
			snippet: "includegraphics[width=${1:0.8\\textwidth}]{${2:image}}$0",
			detail: "Include an image file",
			doc: "Leave the extension off and let the driver pick the best available file. Options: `width`, `height`, `scale`, `angle`, `keepaspectratio`, `trim=l b r t` with `clip`, `page=n` for multi-page PDFs.",
			example: "\\includegraphics[width=\\linewidth]{figures/plot}",
			package: "graphicx",
			context: "text",
		},
		{
			name: "graphicspath",
			snippet: "graphicspath{{${1:figures/}}}$0",
			detail: "Directories to search for images",
			doc: "Note the doubled braces — each path is its own group, and every path must end with a slash: `\\graphicspath{{figures/}{images/}}`.",
			example: "\\graphicspath{{figures/}{plots/}}",
			package: "graphicx",
		},
		{
			name: "DeclareGraphicsExtensions",
			snippet: "DeclareGraphicsExtensions{${1:.pdf,.png,.jpg}}$0",
			detail: "Extension search order for extension-less image names",
			doc: "The order decides which file wins when `plot.pdf` and `plot.png` both exist.",
			example: "\\DeclareGraphicsExtensions{.pdf,.png,.jpg}",
			package: "graphicx",
		},
		{
			name: "DeclareGraphicsRule",
			snippet: "DeclareGraphicsRule{${1:.eps}}{${2:eps}}{${3:.eps}}{}$0",
			detail: "Teach the driver how to handle a file type",
			package: "graphicx",
		},
		{
			name: "rotatebox",
			snippet: "rotatebox[origin=${1:c}]{${2:90}}{$3}$0",
			detail: "Rotate its contents by an angle in degrees",
			doc: "The optional `origin=` picks the pivot (`c`, `l`, `r`, `t`, `b` and combinations). Counter-clockwise for positive angles.",
			example: "\\rotatebox{90}{Sideways heading}",
			package: "graphicx",
			context: "text",
		},
		{
			name: "scalebox",
			snippet: "scalebox{${1:1.5}}{$2}$0",
			detail: "Scale its contents by a factor",
			doc: "A second optional-looking argument scales vertically independently: `\\scalebox{2}[1]{…}` stretches horizontally only.",
			example: "\\scalebox{0.8}{\\input{bigtable}}",
			package: "graphicx",
			context: "text",
		},
		{
			name: "resizebox",
			snippet: "resizebox{${1:\\textwidth}}{${2:!}}{$3}$0",
			detail: "Scale its contents to a given width and height",
			doc: "An exclamation mark for either dimension means 'whatever keeps the aspect ratio'. The standard rescue for a table that is slightly too wide.",
			example: "\\resizebox{\\textwidth}{!}{\\begin{tabular}{lll}…\\end{tabular}}",
			package: "graphicx",
			context: "text",
		},
		{
			name: "reflectbox",
			snippet: "reflectbox{$1}$0",
			detail: "Mirror its contents horizontally",
			doc: "Shorthand for `\\scalebox{-1}[1]{…}`.",
			package: "graphicx",
			context: "text",
		},
		{
			name: "raisebox",
			snippet: "raisebox{${1:0.5ex}}{$2}$0",
			detail: "Shift its contents vertically",
			doc: "The optional arguments override the height and depth the box claims, which is how you raise something without disturbing the line spacing.",
			example: "\\raisebox{-0.3\\height}{\\includegraphics[height=1em]{icon}}",
			package: "graphicx",
			context: "text",
		},
		{
			name: "includegraphics*",
			snippet: "includegraphics*[width=${1:0.8\\textwidth}]{${2:image}}$0",
			detail: "Include an image, clipped to its bounding box",
			doc: "The star is shorthand for `clip`: anything outside the declared bounding box is discarded rather than drawn over the page.",
			package: "graphicx",
			context: "text",
		},
		{
			name: "resizebox*",
			snippet: "resizebox*{${1:\\textwidth}}{${2:!}}{$3}$0",
			detail: "Resize, measuring height as height plus depth",
			doc: "The difference from `\\resizebox` only shows on content with a descender below the baseline.",
			package: "graphicx",
			context: "text",
		},
		{
			name: "setkeys",
			snippet: "setkeys{Gin}{width=${1:0.8\\textwidth}}$0",
			detail: "Set default \\includegraphics options for the rest of the document",
			doc: "The `Gin` family is graphicx's own key family, so this is how you avoid repeating `width=` on every single figure.",
			example: "\\setkeys{Gin}{width=0.9\\linewidth}",
			package: "graphicx",
		},
	],
	environments: [],
};
