import type { PackageData } from "./index";

export const data: PackageData = {
	commands: [
		/* --- paired delimiters --- */
		{
			name: "DeclarePairedDelimiter",
			snippet: "DeclarePairedDelimiter{\\${1:abs}}{${2:\\lvert}}{${3:\\rvert}}$0",
			detail: "Define a scaling delimiter pair",
			doc: "The result takes an optional size: `\\abs{x}` is unscaled, `\\abs*{x}` uses `\\left…\\right`, `\\abs[\\big]{x}` picks a fixed size.",
			example: "\\DeclarePairedDelimiter{\\norm}{\\lVert}{\\rVert}",
			package: "mathtools",
		},
		{
			name: "DeclarePairedDelimiterX",
			snippet: "DeclarePairedDelimiterX{\\${1:innerp}}[${2:2}]{${3:\\langle}}{${4:\\rangle}}{#1,#2}$0",
			detail: "Paired delimiter with several arguments",
			doc: "Use `\\delimsize` inside the body so separators scale with the fences: `{#1\\delimsize\\vert #2}`.",
			package: "mathtools",
		},
		{
			name: "DeclarePairedDelimiterXPP",
			snippet: "DeclarePairedDelimiterXPP{\\${1:name}}[${2:1}]{${3:pre}}{${4:\\lvert}}{${5:\\rvert}}{${6:post}}{#1}$0",
			detail: "Paired delimiter with pre- and post-code",
			package: "mathtools",
		},
		{
			name: "delimsize",
			detail: "The current delimiter size, inside a paired delimiter body",
			package: "mathtools",
			context: "math",
		},

		/* --- smashes and spacing --- */
		{
			name: "mathclap",
			snippet: "mathclap{$1}$0",
			detail: "Zero-width math box, centred",
			doc: "The fix for an over-wide subscript on a sum: `\\sum_{\\mathclap{1\\le i\\le n}}` keeps the limit from stretching the operator's column.",
			example: "\\sum_{\\mathclap{1 \\le i \\le n}} a_i",
			package: "mathtools",
			context: "math",
		},
		{
			name: "mathllap",
			snippet: "mathllap{$1}$0",
			detail: "Zero-width math box overhanging to the left",
			package: "mathtools",
			context: "math",
		},
		{
			name: "mathrlap",
			snippet: "mathrlap{$1}$0",
			detail: "Zero-width math box overhanging to the right",
			package: "mathtools",
			context: "math",
		},
		{
			name: "clap",
			snippet: "clap{$1}$0",
			detail: "Zero-width text box, centred",
			package: "mathtools",
			context: "both",
		},
		{
			name: "mathmakebox",
			snippet: "mathmakebox[${1:width}]{$2}$0",
			detail: "Math box of a given width",
			package: "mathtools",
			context: "math",
		},
		{
			name: "adjustlimits",
			snippet: "adjustlimits{$1}_{$2}{$3}_{$4}$0",
			detail: "Align the limits of two adjacent operators",
			doc: "Levels the subscripts of, say, a `\\lim` followed by a `\\sup` so they sit on one line.",
			example: "\\adjustlimits\\lim_{n\\to\\infty}\\sup_{k\\ge n}",
			package: "mathtools",
			context: "math",
		},
		{
			name: "shortintertext",
			snippet: "shortintertext{$1}$0",
			detail: "Interrupting text with tighter spacing than \\intertext",
			doc: "Inside an `align`-family display only. Same job as amsmath's `\\intertext`, without the generous vertical space.",
			example: "\\shortintertext{and therefore}",
			package: "mathtools",
			context: "math",
		},
		{
			name: "vphantom",
			snippet: "vphantom{$1}$0",
			detail: "Invisible box of the argument's height",
			package: "mathtools",
			context: "math",
		},

		/* --- symbols and constructions --- */
		{
			name: "coloneqq",
			detail: "Definition sign :=",
			doc: "Properly spaced, unlike a hand-typed `:=` whose colon sits too low.",
			example: "f(x) \\coloneqq x^2 + 1",
			package: "mathtools",
			context: "math",
		},
		{
			name: "eqqcolon",
			detail: "Reversed definition sign =:",
			package: "mathtools",
			context: "math",
		},
		{
			name: "colonapprox",
			detail: "Colon followed by approximately-equal",
			package: "mathtools",
			context: "math",
		},
		{
			name: "dblcolon",
			detail: "Double colon ::",
			package: "mathtools",
			context: "math",
		},
		{
			name: "prescript",
			snippet: "prescript{${1:a}}{${2:b}}{${3:X}}$0",
			detail: "Sub- and superscript before a symbol",
			doc: "Left superscript, left subscript, then the symbol — the readable way to write a pre-indexed tensor.",
			example: "\\prescript{14}{6}{\\mathrm{C}}",
			package: "mathtools",
			context: "math",
		},
		{
			name: "xrightarrow",
			snippet: "xrightarrow{$1}$0",
			detail: "Right arrow stretched to fit a label",
			doc: "Optional argument labels below: `\\xrightarrow[below]{above}`.",
			example: "A \\xrightarrow[\\text{heat}]{\\text{catalyst}} B",
			package: "mathtools",
			context: "math",
		},
		{
			name: "xleftarrow",
			snippet: "xleftarrow{$1}$0",
			detail: "Left arrow stretched to fit a label",
			package: "mathtools",
			context: "math",
		},
		{
			name: "xleftrightarrow",
			snippet: "xleftrightarrow{$1}$0",
			detail: "Stretchable left-right arrow with a label",
			package: "mathtools",
			context: "math",
		},
		{
			name: "xhookrightarrow",
			snippet: "xhookrightarrow{$1}$0",
			detail: "Stretchable hooked right arrow with a label",
			package: "mathtools",
			context: "math",
		},
		{
			name: "xmapsto",
			snippet: "xmapsto{$1}$0",
			detail: "Stretchable maps-to arrow with a label",
			package: "mathtools",
			context: "math",
		},
		{
			name: "overbracket",
			snippet: "overbracket{$1}$0",
			detail: "Square bracket over an expression",
			doc: "Rule thickness and bracket height are optional: `\\overbracket[1pt][4pt]{…}`.",
			example: "\\overbracket{a + b}^{\\text{sum}}",
			package: "mathtools",
			context: "math",
		},
		{
			name: "underbracket",
			snippet: "underbracket{$1}$0",
			detail: "Square bracket under an expression",
			package: "mathtools",
			context: "math",
		},
		{
			name: "underbrace",
			snippet: "underbrace{$1}_{$2}$0",
			detail: "Curly brace under an expression, with a label",
			package: "mathtools",
			context: "math",
		},
		{
			name: "splitfrac",
			snippet: "splitfrac{$1}{$2}$0",
			detail: "Split a long numerator or denominator over two lines",
			doc: "`\\splitdfrac` is the display-style version. Both go inside a `\\frac` argument, not around it.",
			example: "\\frac{\\splitfrac{a + b + c}{{}+ d + e}}{f}",
			package: "mathtools",
			context: "math",
		},
		{
			name: "splitdfrac",
			snippet: "splitdfrac{$1}{$2}$0",
			detail: "Display-style split numerator or denominator",
			package: "mathtools",
			context: "math",
		},
		{
			name: "cramped",
			snippet: "cramped{$1}$0",
			detail: "Typeset in cramped style, lowering superscripts",
			package: "mathtools",
			context: "math",
		},
		{
			name: "smashoperator",
			snippet: "smashoperator{$1}$0",
			detail: "Ignore the width of an operator's limits",
			doc: "Optional `[l]`, `[r]` or `[lr]` chooses which side to smash.",
			example: "\\smashoperator{\\sum_{1 \\le i \\le n}} a_i",
			package: "mathtools",
			context: "math",
		},

		/* --- tags, numbering and setup --- */
		{
			name: "mathtoolsset",
			snippet: "mathtoolsset{${1:showonlyrefs}}$0",
			detail: "Configure mathtools",
			doc: "Keys include `showonlyrefs` (number only the equations that are actually referenced), `showmanualtags`, and `mathic`.",
			example: "\\mathtoolsset{showonlyrefs, showmanualtags}",
			package: "mathtools",
		},
		{
			name: "refeq",
			snippet: "refeq{$1}$0",
			detail: "Reference an equation under showonlyrefs",
			package: "mathtools",
			context: "text",
		},
		{
			name: "newtagform",
			snippet: "newtagform{${1:name}}{${2:(}}{${3:)}}$0",
			detail: "Define a format for equation tags",
			example: "\\newtagform{brackets}{[}{]}",
			package: "mathtools",
		},
		{
			name: "usetagform",
			snippet: "usetagform{${1:name}}$0",
			detail: "Switch to a tag format defined by \\newtagform",
			package: "mathtools",
		},
		{
			name: "DeclareMathOperator",
			snippet: "DeclareMathOperator{\\${1:argmin}}{${2:arg\\,min}}$0",
			detail: "Define an upright operator name",
			doc: "The starred form takes limits above and below in display style: `\\DeclareMathOperator*{\\argmin}{arg\\,min}`.",
			example: "\\DeclareMathOperator*{\\argmax}{arg\\,max}",
			package: "mathtools",
		},
		{
			name: "MoveEqLeft",
			detail: "Pull the first line of a long aligned equation left",
			doc: "Opens the first row of an `align`; the optional argument sets how far: `\\MoveEqLeft[3]`.",
			example: "\\MoveEqLeft f(x, y, z) = \\dots",
			package: "mathtools",
			context: "math",
		},
	],
	environments: [
		{
			name: "dcases",
			detail: "Case distinction typeset in display style",
			body: "\n\t$1 & \\text{if } $2 \\\\\n\t$0\n",
			package: "mathtools",
			context: "math",
		},
		{
			name: "dcases*",
			detail: "Display-style cases with upright condition text",
			body: "\n\t$1 & $2 \\\\\n\t$0\n",
			package: "mathtools",
			context: "math",
		},
		{
			name: "rcases",
			detail: "Cases with the brace on the right",
			body: "\n\t$1 \\\\\n\t$0\n",
			package: "mathtools",
			context: "math",
		},
		{
			name: "drcases",
			detail: "Right-braced cases in display style",
			body: "\n\t$1 \\\\\n\t$0\n",
			package: "mathtools",
			context: "math",
		},
		{
			name: "cases*",
			detail: "Cases with the condition column in upright text",
			body: "\n\t$1 & $2 \\\\\n\t$0\n",
			package: "mathtools",
			context: "math",
		},
		{
			name: "multlined",
			detail: "multline that can nest inside another display",
			body: "\n\t$0\n",
			package: "mathtools",
			context: "math",
		},
		{
			name: "lgathered",
			detail: "gathered block aligned left",
			body: "\n\t$0\n",
			package: "mathtools",
			context: "math",
		},
		{
			name: "rgathered",
			detail: "gathered block aligned right",
			body: "\n\t$0\n",
			package: "mathtools",
			context: "math",
		},
		{
			name: "psmallmatrix",
			detail: "Inline-sized matrix in parentheses",
			body: "\n\t$0\n",
			package: "mathtools",
			context: "math",
		},
		{
			name: "bsmallmatrix",
			detail: "Inline-sized matrix in square brackets",
			body: "\n\t$0\n",
			package: "mathtools",
			context: "math",
		},
		{
			name: "vsmallmatrix",
			detail: "Inline-sized matrix in single bars",
			body: "\n\t$0\n",
			package: "mathtools",
			context: "math",
		},
		{
			name: "pmatrix*",
			detail: "Parenthesised matrix with a column alignment",
			body: "[${1:r}]\n\t$0\n",
			package: "mathtools",
			context: "math",
		},
		{
			name: "bmatrix*",
			detail: "Bracketed matrix with a column alignment",
			body: "[${1:r}]\n\t$0\n",
			package: "mathtools",
			context: "math",
		},
		{
			name: "vmatrix*",
			detail: "Bar-delimited matrix with a column alignment",
			body: "[${1:r}]\n\t$0\n",
			package: "mathtools",
			context: "math",
		},
		{
			name: "matrix*",
			detail: "Undelimited matrix with a column alignment",
			body: "[${1:r}]\n\t$0\n",
			package: "mathtools",
			context: "math",
		},
		{
			name: "spreadlines",
			detail: "Set the line spacing of the displays inside",
			body: "{${1:1.3\\baselineskip}}\n\t$0\n",
			package: "mathtools",
			context: "math",
		},
	],
};
