import type { PackageData } from "./index";

// Needs Pygments installed and compilation with `-shell-escape`.
export const data: PackageData = {
	commands: [
		{
			name: "mint",
			snippet: "mint{${1:python}}|$2|$0",
			detail: "A short piece of code, highlighted",
			doc: "The language comes first, then the code between any pair of matching delimiters. For more than a line or two use the `minted` environment instead.",
			example: "\\mint{python}|print(\"hi\")|",
			package: "minted",
			context: "text",
		},
		{
			name: "mintinline",
			snippet: "mintinline{${1:python}}|$2|$0",
			detail: "Inline highlighted code, inside a paragraph",
			doc: "The minted counterpart to `\\verb`. Unlike `\\mint` it does not start a new line, so it belongs in running text.",
			example: "call \\mintinline{python}|list.append(x)| to add",
			package: "minted",
			context: "text",
		},
		{
			name: "inputminted",
			snippet: "inputminted[${1:linenos}]{${2:python}}{${3:file.py}}$0",
			detail: "Highlight a source file from disk",
			doc: "`firstline`/`lastline` extract a range, so the document quotes the real file rather than a stale copy of it.",
			example: "\\inputminted[linenos, firstline=10, lastline=25]{python}{app.py}",
			package: "minted",
			context: "text",
		},
		{
			name: "setminted",
			snippet: "setminted{${1:fontsize=\\small, linenos, breaklines}}$0",
			detail: "Set minted options globally, or per language",
			doc: "Options: `linenos`, `numbersep`, `breaklines`, `fontsize`, `bgcolor`, `frame=lines`, `tabsize`, `autogobble` (strips the common indentation — well worth it). A language in the optional argument scopes the settings: `\\setminted[python]{…}`.",
			example: "\\setminted{fontsize=\\small, breaklines, autogobble}",
			package: "minted",
		},
		{
			name: "setmintedinline",
			snippet: "setmintedinline{${1:bgcolor=}}$0",
			detail: "Set options for inline code only",
			doc: "Inline code usually wants a different background and no frame from the block settings.",
			package: "minted",
		},
		{
			name: "usemintedstyle",
			snippet: "usemintedstyle{${1:friendly}}$0",
			detail: "Choose a Pygments colour style",
			doc: "Any Pygments style name: `default`, `friendly`, `colorful`, `monokai`, `tango`, `vs`, `bw` (for print). `pygmentize -L styles` lists them.",
			example: "\\usemintedstyle{tango}",
			package: "minted",
		},
		{
			name: "newminted",
			snippet: "newminted{${1:python}}{${2:linenos}}$0",
			detail: "Define a per-language environment with preset options",
			doc: "Creates `pythoncode` (and `pythoncode*`), which saves repeating the language on every block.",
			example: "\\newminted{python}{linenos, autogobble}",
			package: "minted",
		},
		{
			name: "newmint",
			snippet: "newmint{${1:python}}{${2:}}$0",
			detail: "Define a shorthand macro for \\mint in one language",
			package: "minted",
		},
		{
			name: "newmintinline",
			snippet: "newmintinline{${1:python}}{${2:}}$0",
			detail: "Define a shorthand macro for \\mintinline in one language",
			doc: "`\\newmintinline{python}{}` gives you `\\pythoninline|…|`.",
			package: "minted",
		},
		{
			name: "newmintedfile",
			snippet: "newmintedfile{${1:python}}{${2:linenos}}$0",
			detail: "Define a shorthand macro for \\inputminted in one language",
			package: "minted",
		},
		{
			name: "listoflistings",
			detail: "Insert the list of listings",
			package: "minted",
			context: "text",
		},
		{
			name: "listingscaption",
			detail: "The caption word for minted listings",
			doc: "Change it with `\\renewcommand{\\listingscaption}{Code}`.",
			package: "minted",
		},
		{
			name: "listoflistingscaption",
			detail: "Heading of the list of listings",
			package: "minted",
		},
	],
	environments: [
		{
			name: "minted",
			detail: "Code block highlighted by Pygments",
			body: "{${1:python}}\n$0\n",
			package: "minted",
			context: "text",
		},
		{
			name: "mintedbox",
			detail: "Framed minted block (minted 3 / mintedbox)",
			body: "{${1:python}}\n$0\n",
			package: "minted",
			context: "text",
		},
		{
			name: "listing",
			detail: "Float wrapping a code block, with caption and label",
			body: "[${1:htbp}]\n\t$0\n\t\\caption{}\n\t\\label{lst:}\n",
			package: "minted",
			context: "text",
		},
	],
};
