import type { PackageData } from "./index";

// Mutually exclusive with `biblatex` — loading both is an error.
export const data: PackageData = {
	commands: [
		{
			name: "citet",
			snippet: "citet{$1}$0",
			detail: "Textual citation — Author (year)",
			doc: "Reads as part of the sentence. Optional arguments are prenote and postnote: `\\citet[chap.~2]{key}`.",
			example: "\\citet{knuth1984} showed that \\dots",
			package: "natbib",
			context: "text",
		},
		{
			name: "citep",
			snippet: "citep{$1}$0",
			detail: "Parenthetical citation — (Author, year)",
			doc: "`\\citep[see][p.~5]{key}` gives “(see Author, year, p. 5)”. Comma-separate keys for a merged citation.",
			example: "This is well established \\citep[p.~5]{knuth1984}.",
			package: "natbib",
			context: "text",
		},
		{
			name: "citet*",
			snippet: "citet*{$1}$0",
			detail: "Textual citation with the full author list",
			package: "natbib",
			context: "text",
		},
		{
			name: "citep*",
			snippet: "citep*{$1}$0",
			detail: "Parenthetical citation with the full author list",
			package: "natbib",
			context: "text",
		},
		{
			name: "citealt",
			snippet: "citealt{$1}$0",
			detail: "Textual citation without parentheses",
			doc: "“Author year” with no punctuation of its own — for building a citation into custom surrounding text.",
			example: "(see \\citealt{knuth1984})",
			package: "natbib",
			context: "text",
		},
		{
			name: "citealp",
			snippet: "citealp{$1}$0",
			detail: "Parenthetical citation without the parentheses",
			doc: "“Author, year” — same as `\\citep` minus the brackets, so several can be combined by hand.",
			example: "(\\citealp{knuth1984}; \\citealp{lamport1994})",
			package: "natbib",
			context: "text",
		},
		{
			name: "citealt*",
			snippet: "citealt*{$1}$0",
			detail: "Bracket-less textual citation, full author list",
			package: "natbib",
			context: "text",
		},
		{
			name: "citealp*",
			snippet: "citealp*{$1}$0",
			detail: "Bracket-less parenthetical citation, full author list",
			package: "natbib",
			context: "text",
		},
		{
			name: "citeauthor",
			snippet: "citeauthor{$1}$0",
			detail: "Author name only",
			doc: "`\\citeauthor*{…}` prints the complete author list rather than “et al.”.",
			example: "\\citeauthor{knuth1984} later revised this.",
			package: "natbib",
			context: "text",
		},
		{
			name: "citeauthor*",
			snippet: "citeauthor*{$1}$0",
			detail: "Full author list, no “et al.”",
			package: "natbib",
			context: "text",
		},
		{
			name: "citeyear",
			snippet: "citeyear{$1}$0",
			detail: "Year only, no parentheses",
			package: "natbib",
			context: "text",
		},
		{
			name: "citeyearpar",
			snippet: "citeyearpar{$1}$0",
			detail: "Year only, in parentheses",
			example: "Knuth's later work \\citeyearpar{knuth1984}",
			package: "natbib",
			context: "text",
		},
		{
			name: "citenum",
			snippet: "citenum{$1}$0",
			detail: "Bare citation number",
			doc: "Numeric styles only — gives the number with no brackets, for use inside custom markup.",
			package: "natbib",
			context: "text",
		},
		{
			name: "citetext",
			snippet: "citetext{$1}$0",
			detail: "Arbitrary text in citation brackets",
			example: "\\citep[see][]{a} \\citetext{and references therein}",
			package: "natbib",
			context: "text",
		},
		{
			name: "defcitealias",
			snippet: "defcitealias{${1:key}}{${2:Alias}}$0",
			detail: "Give an entry a fixed citation alias",
			doc: "Cite it afterwards with `\\citetalias` / `\\citepalias` — the usual way to cite a statute or standard by short name.",
			example: "\\defcitealias{iso8601}{ISO~8601}",
			package: "natbib",
		},
		{
			name: "citetalias",
			snippet: "citetalias{$1}$0",
			detail: "Textual citation using a defined alias",
			package: "natbib",
			context: "text",
		},
		{
			name: "citepalias",
			snippet: "citepalias{$1}$0",
			detail: "Parenthetical citation using a defined alias",
			package: "natbib",
			context: "text",
		},
		{
			name: "bibpunct",
			snippet: "bibpunct{${1:(}}{${2:)}}{${3:;}}{${4:a}}{${5:,}}{${6:,}}$0",
			detail: "Set citation punctuation (open, close, between, style, author–year, years)",
			doc: "The fourth argument selects the style: `a` author–year, `n` numerical, `s` superscript. Preamble only, after `\\usepackage{natbib}`.",
			example: "\\bibpunct{[}{]}{;}{a}{,}{,}",
			package: "natbib",
		},
		{
			name: "setcitestyle",
			snippet: "setcitestyle{$0}",
			detail: "Set citation style by keyword",
			doc: "The readable alternative to `\\bibpunct`: `authoryear`/`numbers`/`super`, `round`/`square`/`open={}`/`close={}`, `semicolon`/`comma`, `aysep={}`, `yysep={}`, `notesep={}`.",
			example: "\\setcitestyle{authoryear,round,aysep={},yysep={;}}",
			package: "natbib",
		},
		{
			name: "citestyle",
			snippet: "citestyle{${1:plainnat}}$0",
			detail: "Adopt the citation style of a named bibliography style",
			package: "natbib",
		},
		{
			name: "bibsection",
			detail: "Sectioning command used for the bibliography heading",
			doc: "Redefine it to control how the reference list heading is typeset, e.g. `\\renewcommand{\\bibsection}{\\section*{References}}`.",
			package: "natbib",
		},
		{
			name: "bibhang",
			detail: "Hanging indent of bibliography entries",
			doc: "A length: `\\setlength{\\bibhang}{2em}`.",
			package: "natbib",
		},
		{
			name: "bibsep",
			detail: "Vertical space between bibliography entries",
			doc: "A length: `\\setlength{\\bibsep}{0pt}` for a tight reference list.",
			package: "natbib",
		},
	],
	environments: [],
};
