import type { PackageData } from "./index";

export const data: PackageData = {
	commands: [
		{
			name: "pgfplotsset",
			snippet: "pgfplotsset{compat=${1:1.18}}$0",
			detail: "Set pgfplots options globally, or define a style",
			doc: "The `compat` key belongs in every preamble. Styles work as in TikZ, and `every axis/.append style={…}` reaches all axes at once.",
			example: "\\pgfplotsset{compat=1.18, every axis/.append style={grid=major}}",
			package: "pgfplots",
		},
		{
			name: "usepgfplotslibrary",
			snippet: "usepgfplotslibrary{${1:groupplots}}$0",
			detail: "Load a pgfplots library",
			doc: "`groupplots` (grids of axes), `fillbetween` (shade between two curves), `statistics` (box plots), `polar`, `dateplot`, `colormaps`, `smithchart`.",
			example: "\\usepgfplotslibrary{groupplots, fillbetween}",
			package: "pgfplots",
		},
		{
			name: "addplot",
			snippet: "addplot[${1:blue, thick}] {${2:x^2}};$0",
			detail: "Add a 2D plot to the current axis",
			doc: "The argument picks the source: `{expr}` for a function, `table {file.dat}` for a data file, `coordinates {(0,0) (1,1)}` for literal points. Sampling a function needs a `domain`.",
			example: "\\addplot[red, mark=*] table[x=t, y=v] {data.dat};",
			package: "pgfplots",
		},
		{
			name: "addplot+",
			snippet: "addplot+[${1:mark=none}] {${2:x}};$0",
			detail: "Plot keeping the cycle-list style, overriding only what you name",
			doc: "`\\addplot[…]` throws the automatic style away; `\\addplot+[…]` keeps the colour and mark the cycle list picked and merges your options on top.",
			example: "\\addplot+[mark=none] table {data.dat};",
			package: "pgfplots",
		},
		{
			name: "addplot3",
			snippet: "addplot3[${1:surf}] {${2:x^2 + y^2}};$0",
			detail: "Add a 3D plot to the current axis",
			doc: "Wants a style such as `surf`, `mesh` or `contour prepared`, plus `domain` and `y domain` to bound the sampling.",
			example: "\\addplot3[surf, domain=-2:2] {x^2 - y^2};",
			package: "pgfplots",
		},
		{
			name: "addplotgraphics",
			snippet: "addplotgraphics[xmin=${1:0}, xmax=${2:1}, ymin=${3:0}, ymax=${4:1}]{${5:image}}$0",
			detail: "Place an image into the axis coordinate system",
			doc: "For putting a real axis around an exported bitmap plot.",
			package: "pgfplots",
		},
		{
			name: "closedcycle",
			detail: "Close the preceding plot down to the axis",
			doc: "Written after the plot's argument, before the semicolon, to turn a curve into a fillable area.",
			example: "\\addplot[fill=blue!20] {sin(deg(x))} \\closedcycle;",
			package: "pgfplots",
		},
		{
			name: "addlegendentry",
			snippet: "addlegendentry{$1}$0",
			detail: "Name the plot that was just added",
			doc: "Goes immediately after its `\\addplot`. The alternative is to set them all at once with the axis option `legend entries=`.",
			example: "\\addlegendentry{Measured}",
			package: "pgfplots",
		},
		{
			name: "addlegendentryexpanded",
			snippet: "addlegendentryexpanded{$1}$0",
			detail: "Legend entry, expanded before it is stored",
			doc: "Use when the label contains a loop variable or macro that must be expanded here rather than when the legend is typeset.",
			package: "pgfplots",
		},
		{
			name: "addlegendimage",
			snippet: "addlegendimage{${1:blue, mark=*}}$0",
			detail: "Add a legend key with no plot behind it",
			doc: "The way to hand-build a legend, or to describe something you drew with plain TikZ.",
			example: "\\addlegendimage{dashed, black}",
			package: "pgfplots",
		},
		{
			name: "legend",
			snippet: "legend{${1:first, second}}$0",
			detail: "Set every legend entry at once",
			doc: "A comma-separated list in plot order; an entry containing a comma must be braced.",
			example: "\\legend{$x$, $x^2$, $x^3$}",
			package: "pgfplots",
		},
		{
			name: "nextgroupplot",
			snippet: "nextgroupplot[$1]$0",
			detail: "Start the next cell of a groupplot",
			doc: "Needs `\\usepgfplotslibrary{groupplots}`. Every cell of the `groupplot` environment is opened by one of these, carrying that cell's own options.",
			example: "\\nextgroupplot[title=Second panel, ylabel={$v$}]",
			package: "pgfplots",
		},
		{
			name: "pgfplotsextra",
			snippet: "pgfplotsextra{$1}$0",
			detail: "Run raw TikZ code inside an axis",
			doc: "Deferred until the axis limits are known, so the code may use axis coordinates.",
			package: "pgfplots",
		},
		{
			name: "pgfplotsinvokeforeach",
			snippet: "pgfplotsinvokeforeach{${1:1,2,3}}{\n\t$0\n}",
			detail: "Loop that is safe around \\addplot",
			doc: "A plain `\\foreach` groups its body and breaks `\\addplot`; this one expands properly, with `#1` standing for the current value.",
			example: "\\pgfplotsinvokeforeach{1,...,3}{\\addplot {x^#1};}",
			package: "pgfplots",
		},
		{
			name: "pgfplotsforeachungrouped",
			snippet: "pgfplotsforeachungrouped \\i in {${1:1,2,3}} {\n\t$0\n}",
			detail: "Loop without opening a group, with a named variable",
			doc: "The other `\\addplot`-safe loop; prefer it when you want `\\i` rather than `#1`.",
			example: "\\pgfplotsforeachungrouped \\f in {a,b} {\\addplot table {\\f.dat};}",
			package: "pgfplots",
		},
		{
			name: "pgfplotscreateplotcyclelist",
			snippet: "pgfplotscreateplotcyclelist{${1:mylist}}{\n\tblue, mark=*\\\\\n\tred, mark=square*\\\\\n}$0",
			detail: "Define a named cycle list of plot styles",
			doc: "Select it afterwards with the axis option `cycle list name=mylist`. Entries are separated by `\\\\`, and the last one needs a trailing `\\\\` too.",
			package: "pgfplots",
		},
		{
			name: "coordinate",
			snippet: "coordinate (${1:name}) at (axis cs:${2:0},${3:0});$0",
			detail: "Name a point on the plot's own scale",
			doc: "`axis cs:` reads the numbers as data coordinates; a bare `(0,0)` would mean canvas centimetres. `rel axis cs:` runs 0–1 across the axis box instead.",
			example: "\\coordinate (peak) at (axis cs:3,9);",
			package: "pgfplots",
		},
		{
			name: "node",
			snippet: "node[$1] at (axis cs:${2:0},${3:0}) {$4};$0",
			detail: "Place a node at a data coordinate",
			doc: "Annotations belong inside the axis so they move with the data; `rel axis cs:` pins them to the axis box instead.",
			example: "\\node[pin=90:{Max}] at (axis cs:3,9) {};",
			package: "pgfplots",
		},
		{
			name: "pgfplotstableread",
			snippet: "pgfplotstableread{${1:data.dat}}{\\${2:table}}$0",
			detail: "Read a data file into a table macro (pgfplotstable)",
			doc: "Needs `\\usepackage{pgfplotstable}`. Reading once and reusing the macro beats re-reading the file for every plot.",
			example: "\\pgfplotstableread{results.dat}{\\results}",
			package: "pgfplots",
		},
		{
			name: "pgfplotstabletypeset",
			snippet: "pgfplotstabletypeset[${1:col sep=comma}]{${2:data.csv}}$0",
			detail: "Typeset a data file as a LaTeX table (pgfplotstable)",
			doc: "`string type` stops it trying to reformat text columns; `columns={a,b}` picks a subset.",
			example: "\\pgfplotstabletypeset[col sep=comma, string type]{results.csv}",
			package: "pgfplots",
		},
		{
			name: "pgfplotstableset",
			snippet: "pgfplotstableset{${1:col sep=comma}}$0",
			detail: "Set pgfplotstable options globally",
			package: "pgfplots",
		},
		{
			name: "pgfplotstablecreatecol",
			snippet: "pgfplotstablecreatecol[${1:expr={\\thisrow{a}*2}}]{${2:new}}{${3:data.dat}}$0",
			detail: "Compute a new column from the existing ones",
			doc: "`\\thisrow{name}` reads another column of the same row inside the expression.",
			package: "pgfplots",
		},
		{
			name: "pgfplotstablegetelem",
			snippet: "pgfplotstablegetelem{${1:0}}{${2:col}}\\of{${3:\\table}}$0",
			detail: "Read one cell into \\pgfplotsretval",
			package: "pgfplots",
		},
		{
			name: "pgfplotstablegetrowsof",
			snippet: "pgfplotstablegetrowsof{${1:data.dat}}$0",
			detail: "Count a table's rows into \\pgfplotsretval",
			package: "pgfplots",
		},
		{
			name: "pgfplotstablevertcat",
			snippet: "pgfplotstablevertcat{\\${1:out}}{${2:data.dat}}$0",
			detail: "Append one table below another",
			package: "pgfplots",
		},
		{
			name: "pgfplotstabletranspose",
			snippet: "pgfplotstabletranspose{\\${1:out}}{${2:data.dat}}$0",
			detail: "Swap a table's rows and columns",
			package: "pgfplots",
		},
		{
			name: "pgfplotstablesave",
			snippet: "pgfplotstablesave{${1:\\table}}{${2:out.dat}}$0",
			detail: "Write a table back out to a file",
			package: "pgfplots",
		},
		{
			name: "pgfplotsretval",
			detail: "Result of the last pgfplotstable query",
			doc: "Overwritten by the next query, so copy it into your own macro if you need it later.",
			package: "pgfplots",
		},
	],
	environments: [
		{
			name: "axis",
			detail: "PGFPlots axis (inside a tikzpicture)",
			body: "[$1]\n\t$0\n",
			package: "pgfplots",
			context: "text",
		},
		{
			name: "semilogxaxis",
			detail: "Axis with a logarithmic x scale",
			body: "[$1]\n\t$0\n",
			package: "pgfplots",
			context: "text",
		},
		{
			name: "semilogyaxis",
			detail: "Axis with a logarithmic y scale",
			body: "[$1]\n\t$0\n",
			package: "pgfplots",
			context: "text",
		},
		{
			name: "loglogaxis",
			detail: "Axis with both scales logarithmic",
			body: "[$1]\n\t$0\n",
			package: "pgfplots",
			context: "text",
		},
		{
			name: "groupplot",
			detail: "Grid of axes; each cell opens with \\nextgroupplot",
			body: "[group style={group size=${1:2 by 2}}]\n\t\\nextgroupplot\n\t\t$0\n",
			package: "pgfplots",
			context: "text",
		},
		{
			name: "polaraxis",
			detail: "Polar axis (polar library)",
			body: "[$1]\n\t$0\n",
			package: "pgfplots",
			context: "text",
		},
	],
};
