/**
 * `pgfplots` — plots drawn by TeX itself, on top of TikZ.
 *
 * Every plot lives in an `axis` (or one of its log-scale siblings) inside a
 * `tikzpicture`; `\addplot` is the one command you cannot avoid. Always pin the
 * behaviour with `\pgfplotsset{compat=1.18}` in the preamble — without it
 * pgfplots emits a warning and keeps ancient defaults.
 */
import type { PackageData } from "./index";

export const data: PackageData = {
	commands: [
		{
			name: "pgfplotsset",
			snippet: "pgfplotsset{compat=${1:1.18}}$0",
			detail: "Set pgfplots options globally, or define a style",
			doc: "The `compat` key belongs in every preamble. Styles work as in TikZ: `\\pgfplotsset{mystyle/.style={grid=major}}`.",
			example: "\\pgfplotsset{compat=1.18, every axis/.append style={grid=major}}",
			package: "pgfplots",
		},
		{
			name: "addplot",
			snippet: "addplot[${1:blue, thick}] {${2:x^2}};$0",
			detail: "Add a 2D plot to the current axis",
			doc: "The argument decides the source: `{expr}` for a function, `table {file.dat}` for data, `coordinates {(0,0) (1,1)}` for literal points. A trailing `\\addlegendentry` names it.",
			example: "\\addplot[red, mark=*] table[x=t, y=v] {data.dat};",
			package: "pgfplots",
		},
		{
			name: "addplot3",
			snippet: "addplot3[${1:surf}] {${2:x^2 + y^2}};$0",
			detail: "Add a 3D plot to the current axis",
			doc: "Needs `\\addplot3` plus a style such as `surf`, `mesh` or `contour`; a `domain` and `y domain` bound the sampling.",
			example: "\\addplot3[surf, domain=-2:2] {x^2 - y^2};",
			package: "pgfplots",
		},
		{
			name: "addplotgraphics",
			snippet: "addplotgraphics[xmin=${1:0}, xmax=${2:1}, ymin=${3:0}, ymax=${4:1}]{${5:image}}$0",
			detail: "Place an image inside the axis coordinate system",
			doc: "For overlaying axes on an exported bitmap plot.",
			package: "pgfplots",
		},
		{
			name: "addlegendentry",
			snippet: "addlegendentry{$1}$0",
			detail: "Name the plot that was just added",
			doc: "Goes immediately after its `\\addplot`. Alternatively set them all at once with the `legend entries=` axis option.",
			example: "\\addlegendentry{Measured}",
			package: "pgfplots",
		},
		{
			name: "addlegendentryexpanded",
			snippet: "addlegendentryexpanded{$1}$0",
			detail: "Legend entry, expanded before it is stored",
			doc: "Use when the label contains a macro that must be expanded at this point rather than at legend time.",
			package: "pgfplots",
		},
		{
			name: "addlegendimage",
			snippet: "addlegendimage{${1:blue, mark=*}}$0",
			detail: "Add a legend key without a plot behind it",
			doc: "The way to hand-build a legend, or to describe something drawn with plain TikZ.",
			example: "\\addlegendimage{dashed, black}",
			package: "pgfplots",
		},
		{
			name: "legend",
			snippet: "legend{${1:first, second}}$0",
			detail: "Set every legend entry at once",
			doc: "A comma-separated list, in plot order. Entries containing a comma must be braced.",
			example: "\\legend{$x$, $x^2$, $x^3$}",
			package: "pgfplots",
		},
		{
			name: "addlegendimageplotgraphics",
			snippet: "addlegendimage{${1:empty legend}}$0",
			detail: "Legend key drawn from an explicit style (alias form)",
			package: "pgfplots",
		},
		{
			name: "pgfplotstableread",
			snippet: "pgfplotstableread{${1:data.dat}}{\\${2:table}}$0",
			detail: "Read a data file into a table macro (pgfplotstable)",
			doc: "Needs `\\usepackage{pgfplotstable}`. Reading once and plotting the macro several times beats re-reading the file.",
			package: "pgfplots",
		},
		{
			name: "pgfplotstabletypeset",
			snippet: "pgfplotstabletypeset[${1:col sep=comma}]{${2:data.csv}}$0",
			detail: "Typeset a data file as a LaTeX table (pgfplotstable)",
			example: "\\pgfplotstabletypeset[col sep=comma, string type]{results.csv}",
			package: "pgfplots",
		},
		{
			name: "pgfplotsinvokeforeach",
			snippet: "pgfplotsinvokeforeach{${1:1,2,3}}{\n\t$0\n}",
			detail: "Loop that survives inside an axis",
			doc: "Plain `\\foreach` misbehaves around `\\addplot`; this expands properly, with `#1` standing for the loop value.",
			example: "\\pgfplotsinvokeforeach{1,...,3}{\\addplot {x^#1};}",
			package: "pgfplots",
		},
		{
			name: "pgfplotsforeachungrouped",
			snippet: "pgfplotsforeachungrouped \\i in {${1:1,2,3}} {\n\t$0\n}",
			detail: "Loop without opening a group",
			doc: "The other loop that is safe around `\\addplot`, when you need a named variable rather than `#1`.",
			package: "pgfplots",
		},
		{
			name: "pgfplotsset",
			snippet: "pgfplotsset{every axis/.append style={${1:grid=major}}}$0",
			detail: "Append options to every axis in the document",
			package: "pgfplots",
		},
		{
			name: "nextgroupplot",
			snippet: "nextgroupplot[$1]$0",
			detail: "Start the next cell of a groupplot",
			doc: "Needs `\\usepgfplotslibrary{groupplots}`. Each cell of the `groupplot` environment is opened by one of these, options and all.",
			example: "\\nextgroupplot[title=Second panel]",
			package: "pgfplots",
		},
		{
			name: "usepgfplotslibrary",
			snippet: "usepgfplotslibrary{${1:groupplots}}$0",
			detail: "Load a pgfplots library",
			doc: "`groupplots` (grids of axes), `fillbetween` (shade between two curves), `polar`, `statistics` (box plots), `dateplot`, `colormaps`, `smithchart`.",
			example: "\\usepgfplotslibrary{groupplots, fillbetween}",
			package: "pgfplots",
		},
		{
			name: "pgfplotsextra",
			snippet: "pgfplotsextra{$1}$0",
			detail: "Run raw TikZ code inside an axis",
			doc: "Deferred until the axis limits are known, so the drawing can use axis coordinates.",
			package: "pgfplots",
		},
		{
			name: "pgfplotscolormapdefinemap",
			snippet: "pgfplotsset{colormap={${1:name}}{${2:color(0cm)=(white); color(1cm)=(blue)}}}$0",
			detail: "Define a colormap",
			package: "pgfplots",
		},
		{
			name: "coordinate",
			snippet: "coordinate (${1:name}) at (axis cs:${2:0},${3:0});$0",
			detail: "Name a point in axis coordinates",
			doc: "`axis cs:` interprets the numbers on the plot's own scale; plain `(0,0)` would be canvas centimetres.",
			example: "\\coordinate (peak) at (axis cs:3,9);",
			package: "pgfplots",
		},
		{
			name: "node",
			snippet: "node[$1] at (axis cs:${2:0},${3:0}) {$4};$0",
			detail: "Place a node at an axis coordinate",
			doc: "Use `rel axis cs:` for a position relative to the axis box (0..1) instead of the data scale.",
			example: "\\node[pin=90:Max] at (axis cs:3,9) {};",
			package: "pgfplots",
		},
		{
			name: "pgfplotstableset",
			snippet: "pgfplotstableset{${1:col sep=comma}}$0",
			detail: "Set pgfplotstable options globally",
			package: "pgfplots",
		},
		{
			name: "pgfplotstablegetrowsof",
			snippet: "pgfplotstablegetrowsof{${1:data.dat}}$0",
			detail: "Count the rows of a table into \\pgfplotsretval",
			package: "pgfplots",
		},
		{
			name: "pgfplotsretval",
			detail: "Result of the last pgfplotstable query",
			package: "pgfplots",
		},
		{
			name: "addplusplot",
			snippet: "addplot+[${1:mark=none}] {${2:x}};$0",
			detail: "Plot keeping the cycle-list style, with additions (`\\addplot+`)",
			doc: "`\\addplot[…]` replaces the automatic style; `\\addplot+[…]` keeps the colour and mark from the cycle list and only overrides what you name.",
			example: "\\addplot+[mark=none] table {data.dat};",
			package: "pgfplots",
		},
		{
			name: "closedcycle",
			detail: "Close the last plot down to the axis (`\\closedcycle`)",
			doc: "Written after the plot's argument — `\\addplot {x^2} \\closedcycle;` — to make a filled area.",
			example: "\\addplot[fill=blue!20] {sin(deg(x))} \\closedcycle;",
			package: "pgfplots",
		},
		{
			name: "pgfplotsdrawaxis",
			detail: "Draw the axis lines explicitly (internal)",
			package: "pgfplots",
		},
		{
			name: "pgfplotsautocompletedatapoint",
			detail: "Hook run per data point (advanced)",
			package: "pgfplots",
		},
		{
			name: "label",
			snippet: "label{${1:plot:mine}}$0",
			detail: "Label an axis for later reference",
			doc: "With `\\usepgfplotslibrary{external}` or `refstyle`, an axis can be referred to like any other float.",
			package: "pgfplots",
		},
		{
			name: "pgfplotsforeachungroupedcsv",
			snippet: "pgfplotsforeachungrouped \\f in {${1:a,b}} {\n\t\\addplot table {\\f.dat};\n}$0",
			detail: "Plot one file per loop value",
			package: "pgfplots",
		},
		{
			name: "addplotthreeD",
			snippet: "addplot3[mesh, ${1:domain=-2:2}] {${2:x*y}};$0",
			detail: "3D mesh plot over a domain (`\\addplot3[mesh]`)",
			package: "pgfplots",
		},
	],
	environments: [
		{
			name: "axis",
			detail: "PGFPlots axis (inside a tikzpicture)",
			body: "[$1]\n\t$0\n",
			package: "pgfplots",
			context: "text",
		},
		{
			name: "semilogxaxis",
			detail: "Axis with a logarithmic x scale",
			body: "[$1]\n\t$0\n",
			package: "pgfplots",
			context: "text",
		},
		{
			name: "semilogyaxis",
			detail: "Axis with a logarithmic y scale",
			body: "[$1]\n\t$0\n",
			package: "pgfplots",
			context: "text",
		},
		{
			name: "loglogaxis",
			detail: "Axis with both scales logarithmic",
			body: "[$1]\n\t$0\n",
			package: "pgfplots",
			context: "text",
		},
		{
			name: "groupplot",
			detail: "Grid of axes; each cell opens with \\nextgroupplot",
			body: "[group style={group size=${1:2 by 2}}]\n\t\\nextgroupplot\n\t\t$0\n",
			package: "pgfplots",
			context: "text",
		},
		{
			name: "polaraxis",
			detail: "Polar axis (polar library)",
			body: "[$1]\n\t$0\n",
			package: "pgfplots",
			context: "text",
		},
	],
};
