import type { PackageData } from "./index";

export const data: PackageData = {
	commands: [
		/* --- the modern (v3) interface --- */
		{
			name: "qty",
			snippet: "qty{${1:1.0}}{${2:\\metre\\per\\second}}$0",
			detail: "A number with a unit (v3 spelling; replaces \\SI)",
			doc: "Inserts a non-breaking thin space between value and unit, so the pair never splits across a line. Works in text and in maths.",
			example: "\\qty{9.81}{\\metre\\per\\second\\squared}",
			package: "siunitx",
			context: "both",
		},
		{
			name: "num",
			snippet: "num{${1:1.2e3}}$0",
			detail: "Format a bare number",
			doc: "Handles digit grouping, the decimal marker and exponent notation: `1.2e3` becomes 1.2 × 10³. Also accepts `+-` for uncertainties.",
			example: "\\num{1.2e-4}",
			package: "siunitx",
			context: "both",
		},
		{
			name: "unit",
			snippet: "unit{${1:\\kilogram\\metre\\per\\second}}$0",
			detail: "A unit on its own (v3 spelling; replaces \\si)",
			doc: "Takes either unit macros or the literal form (`kg.m/s`). Use it for a column header or an axis label where there is no number.",
			example: "\\unit{\\kilo\\gram}",
			package: "siunitx",
			context: "both",
		},
		{
			name: "qtyrange",
			snippet: "qtyrange{${1:1}}{${2:10}}{${3:\\metre}}$0",
			detail: "A range of values sharing one unit (replaces \\SIrange)",
			example: "\\qtyrange{10}{20}{\\celsius}",
			package: "siunitx",
			context: "both",
		},
		{
			name: "numrange",
			snippet: "numrange{${1:1}}{${2:10}}$0",
			detail: "A range of bare numbers (replaces \\numrange)",
			package: "siunitx",
			context: "both",
		},
		{
			name: "qtylist",
			snippet: "qtylist{${1:1;2;3}}{${2:\\metre}}$0",
			detail: "A list of values sharing one unit (replaces \\SIlist)",
			doc: "Items are separated by semicolons; siunitx inserts the commas and the final 'and'.",
			example: "\\qtylist{0.1;0.2;0.5}{\\milli\\metre}",
			package: "siunitx",
			context: "both",
		},
		{
			name: "numlist",
			snippet: "numlist{${1:1;2;3}}$0",
			detail: "A list of bare numbers",
			package: "siunitx",
			context: "both",
		},
		{
			name: "ang",
			snippet: "ang{${1:30}}$0",
			detail: "An angle, in degrees or as degrees;minutes;seconds",
			doc: "`\\ang{1;2;3}` typesets 1° 2′ 3″; a single number just gets the degree sign.",
			example: "\\ang{51;28;38}",
			package: "siunitx",
			context: "both",
		},
		{
			name: "complexqty",
			snippet: "complexqty{${1:1+2i}}{${2:\\ohm}}$0",
			detail: "A complex value with a unit",
			package: "siunitx",
			context: "both",
		},

		/* --- the legacy (v2) interface --- */
		{
			name: "SI",
			snippet: "SI{${1:1.0}}{${2:\\metre}}$0",
			detail: "Number with unit — legacy v2 spelling of \\qty",
			doc: "Deprecated since siunitx v3. It still works, but new documents should write `\\qty{…}{…}`.",
			example: "\\SI{9.81}{\\metre\\per\\second\\squared}",
			package: "siunitx",
			context: "both",
		},
		{
			name: "si",
			snippet: "si{${1:\\metre}}$0",
			detail: "Unit alone — legacy v2 spelling of \\unit",
			doc: "Deprecated since siunitx v3 in favour of `\\unit{…}`.",
			package: "siunitx",
			context: "both",
		},
		{
			name: "SIrange",
			snippet: "SIrange{${1:1}}{${2:10}}{${3:\\metre}}$0",
			detail: "Range with a unit — legacy spelling of \\qtyrange",
			package: "siunitx",
			context: "both",
		},
		{
			name: "SIlist",
			snippet: "SIlist{${1:1;2;3}}{${2:\\metre}}$0",
			detail: "List with a unit — legacy spelling of \\qtylist",
			package: "siunitx",
			context: "both",
		},

		/* --- configuration --- */
		{
			name: "sisetup",
			snippet: "sisetup{${1:per-mode=symbol}}$0",
			detail: "Set siunitx options, globally or locally",
			doc: "Worth knowing: `per-mode=symbol|fraction`, `round-mode=places`, `round-precision=2`, `group-digits`, `output-decimal-marker={,}`, `separate-uncertainty`.",
			example: "\\sisetup{per-mode=symbol, round-mode=places, round-precision=2}",
			package: "siunitx",
		},
		{
			name: "DeclareSIUnit",
			snippet: "DeclareSIUnit{\\${1:name}}{${2:symbol}}$0",
			detail: "Define a new unit macro",
			doc: "Preamble only. The new macro then composes with prefixes and `\\per` like any built-in unit.",
			example: "\\DeclareSIUnit{\\bit}{b}",
			package: "siunitx",
		},
		{
			name: "DeclareSIQualifier",
			snippet: "DeclareSIQualifier{\\${1:name}}{${2:abbr}}$0",
			detail: "Define a unit qualifier (e.g. 'per polymer')",
			package: "siunitx",
		},
		{
			name: "tablenum",
			snippet: "tablenum{${1:1.23}}$0",
			detail: "Format a number for alignment in an S column",
			package: "siunitx",
		},

		/* --- unit building blocks --- */
		{
			name: "per",
			detail: "Division in a unit: everything after it is inverted",
			doc: "`per-mode=symbol` renders it as a solidus, `per-mode=fraction` as a real fraction, and the default uses negative exponents.",
			example: "\\unit{\\metre\\per\\second}",
			package: "siunitx",
		},
		{ name: "squared", detail: "Square the preceding unit", example: "\\unit{\\metre\\squared}", package: "siunitx" },
		{ name: "cubed", detail: "Cube the preceding unit", package: "siunitx" },
		{
			name: "tothe",
			snippet: "tothe{${1:4}}$0",
			detail: "Raise the preceding unit to an arbitrary power",
			package: "siunitx",
		},
		{ name: "metre", detail: "SI unit: metre (m)", package: "siunitx" },
		{ name: "meter", detail: "SI unit: metre, US spelling (m)", package: "siunitx" },
		{ name: "second", detail: "SI unit: second (s)", package: "siunitx" },
		{ name: "kilogram", detail: "SI unit: kilogram (kg)", package: "siunitx" },
		{ name: "gram", detail: "SI unit: gram (g)", package: "siunitx" },
		{ name: "ampere", detail: "SI unit: ampere (A)", package: "siunitx" },
		{ name: "kelvin", detail: "SI unit: kelvin (K)", package: "siunitx" },
		{ name: "mole", detail: "SI unit: mole (mol)", package: "siunitx" },
		{ name: "candela", detail: "SI unit: candela (cd)", package: "siunitx" },
		{ name: "celsius", detail: "Degree Celsius (°C)", example: "\\qty{21.5}{\\celsius}", package: "siunitx" },
		{ name: "percent", detail: "Per cent sign, spaced as a unit", example: "\\qty{12}{\\percent}", package: "siunitx" },
		{ name: "hertz", detail: "SI unit: hertz (Hz)", package: "siunitx" },
		{ name: "newton", detail: "SI unit: newton (N)", package: "siunitx" },
		{ name: "joule", detail: "SI unit: joule (J)", package: "siunitx" },
		{ name: "watt", detail: "SI unit: watt (W)", package: "siunitx" },
		{ name: "volt", detail: "SI unit: volt (V)", package: "siunitx" },
		{ name: "ohm", detail: "SI unit: ohm (Ω)", package: "siunitx" },
		{ name: "pascal", detail: "SI unit: pascal (Pa)", package: "siunitx" },
		{ name: "litre", detail: "Litre (L)", package: "siunitx" },
		{
			name: "kilo",
			detail: "SI prefix: kilo (k)",
			doc: "Prefixes attach to the unit that follows: `\\kilo\\metre`. The other common ones are `\\milli`, `\\micro`, `\\nano`, `\\centi`, `\\mega`, `\\giga`.",
			example: "\\qty{5}{\\kilo\\metre}",
			package: "siunitx",
		},
		{ name: "milli", detail: "SI prefix: milli (m)", package: "siunitx" },
		{ name: "micro", detail: "SI prefix: micro (µ)", package: "siunitx" },
		{ name: "nano", detail: "SI prefix: nano (n)", package: "siunitx" },
		{ name: "mega", detail: "SI prefix: mega (M)", package: "siunitx" },
		{ name: "giga", detail: "SI prefix: giga (G)", package: "siunitx" },
	],
	environments: [],
};
