import type { PackageData } from "./index";

export const data: PackageData = {
	commands: [
		/* --- setup --- */
		{
			name: "usetikzlibrary",
			snippet: "usetikzlibrary{${1:arrows.meta, positioning, calc}}$0",
			detail: "Load TikZ libraries",
			doc: "Preamble only. The ones worth knowing: `arrows.meta` (modern arrow tips), `positioning` (`below=1cm of a`), `calc` (`($(a)!0.5!(b)$)`), `shapes.geometric`, `patterns`, `decorations.pathmorphing`, `intersections`, `fit`, `matrix`, `backgrounds`, `external`.",
			example: "\\usetikzlibrary{arrows.meta, positioning, calc}",
			package: "tikz",
		},
		{
			name: "tikzset",
			snippet: "tikzset{${1:every node/.style={draw}}}$0",
			detail: "Set TikZ options globally, or define a named style",
			doc: "The supported replacement for `\\tikzstyle`. A style defined with the `/.style` handler can then be used as a plain option anywhere.",
			example: "\\tikzset{dot/.style={circle, fill, inner sep=1.5pt}}",
			package: "tikz",
		},
		{
			name: "tikzstyle",
			snippet: "tikzstyle{${1:name}} = [$2]$0",
			detail: "Define a reusable style (legacy — prefer \\tikzset)",
			doc: "Still works for old documents, but `\\tikzset{name/.style={…}}` is the spelling TikZ actually supports.",
			package: "tikz",
		},
		{
			name: "tikz",
			snippet: "tikz{$1}$0",
			detail: "A one-off inline picture, without the environment",
			doc: "Convenient for a mark in running text. In the `\\tikz \\draw …;` form the picture ends at the first semicolon.",
			example: "a \\tikz \\draw[fill] (0,0) circle (2pt); dot",
			package: "tikz",
			context: "text",
		},

		/* --- path commands --- */
		{
			name: "draw",
			snippet: "draw[$1] ($2) -- ($3);$0",
			detail: "Stroke a path",
			doc: "The workhorse. Options in brackets, then coordinates joined by path operations: `--` straight, `to[out=,in=]` curved, `|-` right-angled, plus `circle`, `rectangle`, `arc`, `grid`, `plot`.",
			example: "\\draw[thick, ->] (0,0) -- (2,1) arc (0:90:1cm);",
			package: "tikz",
		},
		{
			name: "path",
			snippet: "path[$1] ($2);$0",
			detail: "Build a path without drawing it by default",
			doc: "`\\draw`, `\\fill` and the rest are all `\\path` with an option preset. Used bare to place nodes, or with `name path` for the `intersections` library.",
			example: "\\path (0,0) node (a) {A} (3,0) node (b) {B};",
			package: "tikz",
		},
		{
			name: "fill",
			snippet: "fill[${1:gray!30}] ($2) circle (${3:1cm});$0",
			detail: "Fill a path with a colour",
			example: "\\fill[blue!20] (0,0) rectangle (2,1);",
			package: "tikz",
		},
		{
			name: "filldraw",
			snippet: "filldraw[fill=${1:gray!30}, draw=${2:black}] ($3) circle (${4:1cm});$0",
			detail: "Fill and stroke the same path",
			doc: "Takes separate `fill=` and `draw=` colours; a bare `color=` sets both at once.",
			example: "\\filldraw[fill=yellow!40, draw=black] (0,0) circle (8pt);",
			package: "tikz",
		},
		{
			name: "shade",
			snippet: "shade[${1:left color=white, right color=blue}] ($2) rectangle ($3);$0",
			detail: "Fill a path with a gradient",
			doc: "Three shadings: `axis` (the default, driven by `left`/`right`/`top`/`bottom color`), `radial` (`inner color`/`outer color`) and `ball color`.",
			example: "\\shade[ball color=red] (0,0) circle (1cm);",
			package: "tikz",
		},
		{
			name: "shadedraw",
			snippet: "shadedraw[${1:top color=white, bottom color=gray}] ($2) rectangle ($3);$0",
			detail: "Shade and stroke the same path",
			package: "tikz",
		},
		{
			name: "pattern",
			snippet: "pattern[pattern=${1:north east lines}] ($2) rectangle ($3);$0",
			detail: "Fill a path with a hatch pattern",
			doc: "Needs `\\usetikzlibrary{patterns}`. `pattern color=` tints it; the fill is transparent between the strokes.",
			example: "\\pattern[pattern=dots, pattern color=blue] (0,0) circle (1cm);",
			package: "tikz",
		},
		{
			name: "clip",
			snippet: "clip ($1) rectangle ($2);$0",
			detail: "Restrict all later drawing to this path",
			doc: "Clipping lasts to the end of the enclosing scope, so it is nearly always written inside a `scope`.",
			example: "\\begin{scope}\n\t\\clip (0,0) circle (1cm);\n\t\\fill[red] (-1,-1) rectangle (1,1);\n\\end{scope}",
			package: "tikz",
		},
		{
			name: "useasboundingbox",
			snippet: "useasboundingbox ($1) rectangle ($2);$0",
			detail: "Fix the picture's bounding box to this path",
			doc: "Pins the size, so a picture stops jumping about between beamer overlays or animation frames.",
			example: "\\useasboundingbox (-2,-2) rectangle (2,2);",
			package: "tikz",
		},
		{
			name: "node",
			snippet: "node[$1] at ($2) {$3};$0",
			detail: "Place a node — a box of text, optionally a shape",
			doc: "Standalone it needs `at (…)`; inside a path it takes the current position. A name in parentheses after `node` lets later paths refer to it and its anchors (`a.north`).",
			example: "\\node[draw, circle] (a) at (0,0) {$x$};",
			package: "tikz",
		},
		{
			name: "coordinate",
			snippet: "coordinate (${1:name}) at ($2);$0",
			detail: "Name a point without drawing anything",
			doc: "A node with the `coordinate` shape — zero size, so paths meet it exactly rather than stopping at a border.",
			example: "\\coordinate (origin) at (0,0);",
			package: "tikz",
		},
		{
			name: "matrix",
			snippet: "matrix[${1:matrix of nodes}] {\n\t$0\n};",
			detail: "Lay nodes out in a grid",
			doc: "Needs `\\usetikzlibrary{matrix}`. Rows end with `\\\\`, cells are separated by `&`; `row sep`/`column sep` control the spacing.",
			package: "tikz",
		},
		{
			name: "pic",
			snippet: "pic[$1] {${2:name}};$0",
			detail: "Insert a reusable sub-picture",
			doc: "Defined with `\\tikzset{name/.pic={…}}`. The classic use is a right-angle or angle-arc mark reused all over a diagram.",
			example: "\\pic[draw, angle radius=6mm] {angle=a--b--c};",
			package: "tikz",
		},
		{
			name: "graph",
			snippet: "graph{${1:a -> b -> c}};$0",
			detail: "Terse graph description (graphs library)",
			doc: "Needs `\\usetikzlibrary{graphs}`. Builds nodes and edges from a short description; braces group targets.",
			example: "\\draw \\graph{a -> {b, c} -> d};",
			package: "tikz",
		},
		{
			name: "nodepart",
			snippet: "nodepart{${1:second}}$0",
			detail: "Switch to the next part of a multi-part node",
			doc: "For split shapes such as `rectangle split` or `circle split`.",
			package: "tikz",
		},

		/* --- loops and arithmetic --- */
		{
			name: "foreach",
			snippet: "foreach \\x in {${1:1,...,4}} {\n\t$0\n}",
			detail: "Loop over a list of values",
			doc: "Ranges use `...`; two leading values set the step (`0,2,...,10`). Several variables at once with a slash: `\\foreach \\x/\\y in {1/a, 2/b}`.",
			example: "\\foreach \\x in {0,...,4} \\draw (\\x,0) circle (2pt);",
			package: "tikz",
		},
		{
			name: "pgfmathparse",
			snippet: "pgfmathparse{$1}$0",
			detail: "Evaluate an expression into \\pgfmathresult",
			example: "\\pgfmathparse{2*pi*1.5}",
			package: "tikz",
		},
		{
			name: "pgfmathresult",
			detail: "The result of the last \\pgfmathparse",
			doc: "A macro, not a command — expand it where you need the number. It is overwritten by the next parse, so save it if you need it later.",
			package: "tikz",
		},
		{
			name: "pgfmathsetmacro",
			snippet: "pgfmathsetmacro{\\${1:result}}{${2:2*3}}$0",
			detail: "Evaluate an expression into a macro",
			example: "\\pgfmathsetmacro{\\r}{sqrt(2)}",
			package: "tikz",
		},
		{
			name: "pgfmathsetlengthmacro",
			snippet: "pgfmathsetlengthmacro{\\${1:len}}{${2:0.5*\\textwidth}}$0",
			detail: "Evaluate an expression into a macro holding a length",
			package: "tikz",
		},
		{
			name: "pgfmathtruncatemacro",
			snippet: "pgfmathtruncatemacro{\\${1:n}}{${2:3.7}}$0",
			detail: "Evaluate an expression and truncate it to an integer",
			doc: "The usual way to get a loop counter you can use in a node name, since `\\pgfmathsetmacro` would leave `3.0`.",
			package: "tikz",
		},
		{
			name: "pgfmathrandominteger",
			snippet: "pgfmathrandominteger{\\${1:n}}{${2:1}}{${3:6}}$0",
			detail: "Draw a random integer from a range",
			package: "tikz",
		},

		/* --- keys --- */
		{
			name: "pgfkeys",
			snippet: "pgfkeys{${1:/tikz/key}=${2:value}}$0",
			detail: "Set PGF keys directly",
			doc: "The layer `\\tikzset` is built on. Useful when defining your own key handlers (`/.code`, `/.store in`, `/.default`).",
			package: "tikz",
		},
		{
			name: "pgfkeysvalueof",
			snippet: "pgfkeysvalueof{${1:/tikz/key}}$0",
			detail: "Expand to the current value of a key",
			package: "tikz",
		},

		/* --- layers --- */
		{
			name: "pgfdeclarelayer",
			snippet: "pgfdeclarelayer{${1:background}}$0",
			detail: "Declare a drawing layer",
			doc: "Pair with `\\pgfsetlayers{background,main}` in the preamble, then wrap the drawing in `pgfonlayer`.",
			package: "tikz",
		},
		{
			name: "pgfsetlayers",
			snippet: "pgfsetlayers{${1:background,main}}$0",
			detail: "Set the order layers are drawn in",
			doc: "`main` must appear in the list, and later entries are painted on top.",
			example: "\\pgfsetlayers{background,main,foreground}",
			package: "tikz",
		},
		{
			name: "pgfresetboundingbox",
			detail: "Discard the bounding box computed so far",
			doc: "Followed by `\\useasboundingbox` when a decoration or overlay has blown the box up.",
			package: "tikz",
		},

		/* --- low-level PGF --- */
		{
			name: "pgfpoint",
			snippet: "pgfpoint{${1:1cm}}{${2:1cm}}$0",
			detail: "A point from two explicit lengths (low-level PGF)",
			package: "tikz",
		},
		{
			name: "pgfpointanchor",
			snippet: "pgfpointanchor{${1:node}}{${2:north}}$0",
			detail: "The coordinate of a node's anchor (low-level PGF)",
			package: "tikz",
		},
		{
			name: "pgfpathmoveto",
			snippet: "pgfpathmoveto{$1}$0",
			detail: "Begin a new subpath at a point (low-level PGF)",
			package: "tikz",
		},
		{
			name: "pgfpathlineto",
			snippet: "pgfpathlineto{$1}$0",
			detail: "Extend the path with a straight line (low-level PGF)",
			package: "tikz",
		},
		{
			name: "pgfpathcircle",
			snippet: "pgfpathcircle{$1}{${2:1cm}}$0",
			detail: "Add a circle to the path (low-level PGF)",
			package: "tikz",
		},
		{
			name: "pgfusepath",
			snippet: "pgfusepath{${1:stroke}}$0",
			detail: "Draw the constructed path (low-level PGF)",
			doc: "Takes any of `stroke`, `fill`, `clip`, `discard` — nothing is painted until you say so.",
			package: "tikz",
		},
		{
			name: "pgfnode",
			snippet: "pgfnode{${1:rectangle}}{${2:center}}{${3:text}}{${4:name}}{}$0",
			detail: "Place a node (low-level PGF)",
			package: "tikz",
		},
		{
			name: "pgfsetlinewidth",
			snippet: "pgfsetlinewidth{${1:0.8pt}}$0",
			detail: "Set the stroke width (low-level PGF)",
			package: "tikz",
		},
		{
			name: "pgfsetstrokecolor",
			snippet: "pgfsetstrokecolor{${1:black}}$0",
			detail: "Set the stroke colour (low-level PGF)",
			package: "tikz",
		},
		{
			name: "pgfsetfillcolor",
			snippet: "pgfsetfillcolor{${1:black}}$0",
			detail: "Set the fill colour (low-level PGF)",
			package: "tikz",
		},
		{
			name: "pgftransformrotate",
			snippet: "pgftransformrotate{${1:45}}$0",
			detail: "Rotate the coordinate system (low-level PGF)",
			package: "tikz",
		},
		{
			name: "pgftransformscale",
			snippet: "pgftransformscale{${1:2}}$0",
			detail: "Scale the coordinate system (low-level PGF)",
			package: "tikz",
		},
		{
			name: "pgftransformshift",
			snippet: "pgftransformshift{\\pgfpoint{${1:1cm}}{${2:0cm}}}$0",
			detail: "Shift the coordinate system (low-level PGF)",
			package: "tikz",
		},
		{
			name: "pgfdeclaredecoration",
			snippet: "pgfdeclaredecoration{${1:name}}{${2:initial}}{\n\t$0\n}",
			detail: "Define a custom path decoration",
			package: "tikz",
		},

		/* --- colour --- */
		{
			name: "definecolor",
			snippet: "definecolor{${1:name}}{${2:RGB}}{${3:0,0,0}}$0",
			detail: "Define a colour usable in TikZ options",
			doc: "TikZ loads xcolor, so every model works: `rgb` (0–1), `RGB` (0–255), `HTML`, `gray`, `cmyk`.",
			example: "\\definecolor{brandblue}{HTML}{2A6FDB}",
			package: "tikz",
		},
		{
			name: "colorlet",
			snippet: "colorlet{${1:name}}{${2:blue!40!black}}$0",
			detail: "Name the result of a colour expression",
			example: "\\colorlet{edge}{black!60}",
			package: "tikz",
		},

		/* --- fadings, marks, coordinate systems --- */
		{
			name: "tikzfading",
			snippet: "tikzfading[name=${1:fade out}, inner color=transparent!0, outer color=transparent!100]$0",
			detail: "Define a transparency fade",
			doc: "Needs `\\usetikzlibrary{fadings}`; applied with the `path fading=` option.",
			package: "tikz",
		},
		{
			name: "tikzmark",
			snippet: "tikzmark{${1:name}}$0",
			detail: "Mark a spot in running text for a later picture to find",
			doc: "Needs `\\usetikzlibrary{tikzmark}` and two compilation runs — the position travels through the `.aux` file. Draw to it from a picture with `overlay, remember picture`.",
			example: "the \\tikzmark{here}important word",
			package: "tikz",
			context: "text",
		},
		{
			name: "tikzmarknode",
			snippet: "tikzmarknode{${1:name}}{${2:text}}$0",
			detail: "Typeset text as a named node inside running text or math",
			doc: "Better than `\\tikzmark` when you want to point an arrow at a whole symbol rather than a bare point.",
			example: "$a + \\tikzmarknode{b}{b} = c$",
			package: "tikz",
		},
		{
			name: "tikzdeclarecoordinatesystem",
			snippet: "tikzdeclarecoordinatesystem{${1:name}}{\n\t$0\n}",
			detail: "Define a custom coordinate system",
			doc: "Lets you write `(name cs: …)` alongside the built-in `canvas cs`, `polar cs` and `barycentric cs`.",
			package: "tikz",
		},

		/* --- externalisation --- */
		{
			name: "tikzexternalize",
			detail: "Compile each picture to its own cached PDF",
			doc: "Needs `\\usetikzlibrary{external}` and shell-escape. A document heavy with TikZ recompiles dramatically faster afterwards, because unchanged pictures are simply reused.",
			example: "\\usetikzlibrary{external}\n\\tikzexternalize",
			package: "tikz",
		},
		{
			name: "tikzexternaldisable",
			detail: "Stop externalising the following pictures",
			doc: "Necessary around pictures that use `remember picture`, which cannot be externalised.",
			package: "tikz",
		},
		{ name: "tikzexternalenable", detail: "Resume externalising pictures", package: "tikz" },
		{
			name: "tikzsetnextfilename",
			snippet: "tikzsetnextfilename{${1:figure-name}}$0",
			detail: "Name the externalised file for the next picture",
			doc: "Without it the files are numbered, and inserting a picture renames everything after it.",
			package: "tikz",
		},
		{
			name: "tikzsetfigurename",
			snippet: "tikzsetfigurename{${1:fig-}}$0",
			detail: "Set the prefix for externalised picture files",
			package: "tikz",
		},
	],
	environments: [
		{
			name: "tikzpicture",
			detail: "TikZ drawing",
			body: "[$1]\n\t$0\n",
			package: "tikz",
			context: "text",
		},
		{
			name: "scope",
			detail: "TikZ scope — options, transformations and clipping stay local",
			body: "[$1]\n\t$0\n",
			package: "tikz",
			context: "text",
		},
		{
			name: "pgfonlayer",
			detail: "Draw the contents on a declared layer",
			body: "{${1:background}}\n\t$0\n",
			package: "tikz",
			context: "text",
		},
	],
};
