import type { PackageData } from "./index";

export const data: PackageData = {
	commands: [
		{
			name: "color",
			snippet: "color{${1:red}}$0",
			detail: "Switch the text colour until the end of the group",
			doc: "A switch, not a wrapper — it affects everything after it in the current group. `\\textcolor` is safer in running text.",
			example: "{\\color{red}warning text}",
			package: "xcolor",
			context: "both",
		},
		{
			name: "textcolor",
			snippet: "textcolor{${1:red}}{$2}$0",
			detail: "Set the colour of one piece of text",
			doc: "The optional first argument names a model for a literal value: `\\textcolor[HTML]{2A6FDB}{text}`.",
			example: "\\textcolor{blue!70!black}{emphasis}",
			package: "xcolor",
			context: "both",
		},
		{
			name: "colorbox",
			snippet: "colorbox{${1:yellow}}{$2}$0",
			detail: "Text on a coloured background",
			doc: "The padding comes from `\\fboxsep`, so set that to `0pt` for a tight highlight.",
			example: "\\colorbox{yellow!40}{highlighted}",
			package: "xcolor",
			context: "text",
		},
		{
			name: "fcolorbox",
			snippet: "fcolorbox{${1:black}}{${2:yellow}}{$3}$0",
			detail: "Text on a coloured background with a coloured frame",
			doc: "Frame colour first, then the fill. Frame width is `\\fboxrule`.",
			example: "\\fcolorbox{red}{white}{caution}",
			package: "xcolor",
			context: "text",
		},
		{
			name: "pagecolor",
			snippet: "pagecolor{${1:black!5}}$0",
			detail: "Set the background colour of this and following pages",
			doc: "`\\nopagecolor` restores it. Beamer users normally set the background through the theme instead.",
			package: "xcolor",
		},
		{
			name: "nopagecolor",
			detail: "Restore the default (transparent) page background",
			package: "xcolor",
		},
		{
			name: "definecolor",
			snippet: "definecolor{${1:name}}{${2:RGB}}{${3:0,0,0}}$0",
			detail: "Define a named colour",
			doc: "Models: `rgb` and `cmyk` take fractions 0–1, `RGB` takes integers 0–255, `HTML` takes six hex digits with no `#`, `gray` takes one fraction.",
			example: "\\definecolor{brand}{HTML}{2A6FDB}",
			package: "xcolor",
		},
		{
			name: "providecolor",
			snippet: "providecolor{${1:name}}{${2:RGB}}{${3:0,0,0}}$0",
			detail: "Define a colour only if it does not exist yet",
			package: "xcolor",
		},
		{
			name: "colorlet",
			snippet: "colorlet{${1:name}}{${2:blue!40!black}}$0",
			detail: "Name the result of a colour expression",
			doc: "The right way to build a palette: define the base colours, then derive the rest so one edit updates everything.",
			example: "\\colorlet{shade}{brand!15}",
			package: "xcolor",
		},
		{
			name: "definecolorset",
			snippet: "definecolorset{${1:rgb}}{${2:pre}}{${3:post}}{${4:name,1,0,0}}$0",
			detail: "Define several colours in one model at once",
			package: "xcolor",
		},
		{
			name: "rowcolor",
			snippet: "rowcolor{${1:gray!20}}$0",
			detail: "Colour the current table row",
			doc: "Needs the `table` package option (`\\usepackage[table]{xcolor}`), which loads colortbl. Goes at the very start of the row.",
			example: "\\rowcolor{gray!20} Name & Value \\\\",
			package: "xcolor",
			context: "text",
		},
		{
			name: "rowcolors",
			snippet: "rowcolors{${1:2}}{${2:gray!10}}{${3:white}}$0",
			detail: "Alternate row colours from a starting row",
			doc: "Needs the `table` option. Written before the tabular; the first argument is the row the striping starts on, which is how you skip a header.",
			example: "\\rowcolors{2}{gray!10}{white}",
			package: "xcolor",
			context: "text",
		},
		{
			name: "cellcolor",
			snippet: "cellcolor{${1:red!20}}$0",
			detail: "Colour a single table cell",
			doc: "Needs the `table` option. Placed inside the cell, before its content; it overrides `\\rowcolor`.",
			example: "\\cellcolor{red!20} 42",
			package: "xcolor",
			context: "text",
		},
		{
			name: "columncolor",
			snippet: "columncolor{${1:blue!10}}$0",
			detail: "Colour a table column",
			doc: "Needs the `table` option, and belongs in the column specification via `>{…}`: `>{\\columncolor{blue!10}}l`.",
			example: "\\begin{tabular}{>{\\columncolor{blue!10}}l r}",
			package: "xcolor",
			context: "text",
		},
		{
			name: "arrayrulecolor",
			snippet: "arrayrulecolor{${1:gray}}$0",
			detail: "Colour the rules of a table",
			package: "xcolor",
			context: "text",
		},
		{
			name: "normalcolor",
			detail: "Return to the surrounding default colour",
			package: "xcolor",
			context: "both",
		},
		{
			name: "selectcolormodel",
			snippet: "selectcolormodel{${1:gray}}$0",
			detail: "Convert all following colours to a model",
			doc: "`\\selectcolormodel{gray}` is a quick way to check how a colour document survives black-and-white printing.",
			package: "xcolor",
		},
		{
			name: "extractcolorspec",
			snippet: "extractcolorspec{${1:red}}{\\${2:spec}}$0",
			detail: "Read a colour's model and values into a macro",
			package: "xcolor",
		},
		{
			name: "convertcolorspec",
			snippet: "convertcolorspec{${1:rgb}}{${2:1,0,0}}{${3:HTML}}{\\${4:out}}$0",
			detail: "Convert a colour value between models",
			package: "xcolor",
		},
		{
			name: "blendcolors",
			snippet: "blendcolors{${1:!50!blue}}$0",
			detail: "Blend every following colour with a given one",
			package: "xcolor",
		},
		{
			name: "definecolorseries",
			snippet: "definecolorseries{${1:name}}{${2:rgb}}{${3:last}}{${4:blue}}{${5:red}}$0",
			detail: "Define a colour series that steps through a range",
			doc: "Combined with `\\resetcolorseries`, this is how you get N distinguishable colours without naming them by hand — each use of `name!!+` yields the next one.",
			package: "xcolor",
		},
		{
			name: "resetcolorseries",
			snippet: "resetcolorseries[${1:5}]{${2:name}}$0",
			detail: "Restart a colour series, optionally with a step count",
			package: "xcolor",
		},
		{
			name: "hiderowcolors",
			detail: "Suspend \\rowcolors striping",
			doc: "`\\showrowcolors` turns it back on — useful across a page break in a longtable.",
			package: "xcolor",
			context: "text",
		},
	],
	environments: [],
};
