/** Directories never worth importing: dependency trees, build output, tool caches,
 *  and editor state. Matched at any depth. */
export const IGNORED_DIRS = [
	'node_modules',
	'bower_components',
	'jspm_packages',
	'vendor',
	'.git',
	'.svn',
	'.hg',
	'.next',
	'.nuxt',
	'.svelte-kit',
	'.turbo',
	'.vercel',
	'.netlify',
	'.output',
	'.parcel-cache',
	'.cache',
	'.gradle',
	'.idea',
	'.vscode',
	'.venv',
	'venv',
	'__pycache__',
	'.pytest_cache',
	'.mypy_cache',
	'.tox',
	'target',
	'coverage',
	'.nyc_output',
	'__MACOSX'
];

/** Files that are noise in every archive, plus TeX build artifacts — all of these
 *  are regenerated by a compile, so importing them only burns quota. */
export const IGNORED_FILES = [
	'.DS_Store',
	'Thumbs.db',
	'desktop.ini',
	'*.aux',
	'*.bbl',
	'*.blg',
	'*.fdb_latexmk',
	'*.fls',
	'*.lof',
	'*.lot',
	'*.out',
	'*.synctex.gz',
	'*.toc',
	'*.log'
];

export type IgnoreMatcher = (path: string, isDir?: boolean) => boolean;

type Rule = { re: RegExp; negated: boolean; dirOnly: boolean };

/** Escapes a literal run, leaving `*` / `?` / `**` for the caller to expand. */
function escapeLiteral(segment: string): string {
	return segment.replace(/[.+^${}()|[\]\\]/g, '\\$&');
}

// `**` spans separators, `*` and `?` stop at one. Order matters: `**` is consumed
// before the single-`*` pass so the two don't overwrite each other.
function segmentToRegex(segment: string): string {
	return escapeLiteral(segment)
		.split('**')
		.map((part) => part.replace(/\*/g, '[^/]*').replace(/\?/g, '[^/]'))
		.join('.*');
}

function compileRule(raw: string): Rule | null {
	let pattern = raw.trim();
	if (!pattern || pattern.startsWith('#')) return null;

	const negated = pattern.startsWith('!');
	if (negated) pattern = pattern.slice(1);

	const dirOnly = pattern.endsWith('/');
	if (dirOnly) pattern = pattern.slice(0, -1);
	if (!pattern) return null;

	// A pattern containing a slash anywhere but the end is anchored to the root;
	// a bare name matches at any depth. This is git's rule.
	const anchored = pattern.includes('/');
	if (pattern.startsWith('/')) pattern = pattern.slice(1);

	const body = segmentToRegex(pattern);
	// Match the path itself or anything beneath it, so ignoring `build` also
	// ignores `build/main.pdf`.
	const re = new RegExp(`^${anchored ? '' : '(?:.*/)?'}${body}(?:/.*)?$`);
	return { re, negated, dirOnly };
}

/**
 * Compiles gitignore-style patterns into a matcher. Supports comments, negation,
 * directory-only rules, root anchoring, and `*` / `?` / `**` globs — not the full
 * spec (no character classes, no per-directory nested .gitignore files).
 */
export function compileIgnore(patterns: string[]): IgnoreMatcher {
	const rules = patterns.map(compileRule).filter((r): r is Rule => r !== null);

	return (path: string, isDir = false) => {
		let ignored = false;
		// Last matching rule wins, so a later `!pattern` can rescue a path.
		for (const rule of rules) {
			if (rule.dirOnly && !isDir && !rule.re.test(path)) continue;
			if (!rule.re.test(path)) continue;
			ignored = !rule.negated;
		}
		return ignored;
	};
}

/** The blacklist every import applies, before any project `.gitignore`. */
export const defaultIgnore: IgnoreMatcher = compileIgnore([
	...IGNORED_DIRS.map((d) => `${d}/`),
	...IGNORED_FILES
]);

/** Splits `.gitignore` text into raw patterns. */
export function parseGitignore(text: string): string[] {
	return text.split(/\r?\n/);
}

/**
 * Combines the built-in blacklist with a project's own `.gitignore`, when the
 * import contains one at its root. `.gitignore` itself is always kept — it is a
 * source file, and dropping it would lose the project's own rules.
 */
export function importIgnore(gitignoreText?: string): IgnoreMatcher {
	if (!gitignoreText) return defaultIgnore;
	const project = compileIgnore(parseGitignore(gitignoreText));
	return (path, isDir) => {
		if (path === '.gitignore') return false;
		return defaultIgnore(path, isDir) || project(path, isDir);
	};
}
